### ISSUE TITLE
Won't install Cydia when pressed jailbreak multiple times.

### ISSUE THREAD

**Issue by byt3d3lux3** [Sticktron/g0blin#100]
Model - iPad 9.7 inch/2017 (Not the iPad Pro)
Current iOS Version - 10.3.1

Everytime I press jailbreak, it resprings, and then doesn't install Cydia. I kepp trying and trying and trying. No luck

**Comment by JMccormick264** [comment]
Try going into Safari and opening a new tab. Then in the address bar type in `cydia://` and see if it will open then. Could just not be appearing on homescreen.

**Comment by Kristijan1001** [comment]
that wont fix anything tho, any installed tweaks have no icon either

**Comment by byt3d3lux3** [comment]
Thank you, so much. Theres a new problem that I found at eventually. Installing tweaked apps won't show up so you have to do the same method to open Cydia for example MTerminal://

**Comment by Sticktron** [comment]
#92
