### ISSUE TITLE
Fix for Cydia/Tweak Icons not showing up on springboard on iPads !

### ISSUE THREAD

**Issue by Kristijan1001** [Sticktron/g0blin#102]
DO THIS IF SBShowNonDefaultSystemApps is non existent in : /var/mobile/Library/Preferences/com.apple.springboard.plist

This worked on my iPad Air 10.3.2, I had to do it up until step 12.

Writing this so anyone else who has this problem doesn't struggle and loses their mind trying to fix it. lol

1.Download g0blin and Meridian

2.Jailbreak with g0blin (See Step 8th)

3.Open Cydia through Safari with cydia://

4.Go install Filza File Manager

5.Reboot Tablet

6.Jailbreak with Meridian

7.Reboot

8.You should see Cydia and Filza on the spring board

9.If you don't see the icons, Open Filza and do rest of the steps after (Step 13) if Filza Crashes and doesn't open continue with step 10)

10.If You Don't/Do see them, Remove Cyida and Meridian.

11.Reboot

12.Jailbreak with g0blin with FORCE Re-install Bootstrap (Stop here if your icons showed up, like mine which already did)

13.Open Filza through Safari with filza://

14.Go to /var/mobile/Library/Preferences/com.apple.springboard.plist

15.Open the File and find SBShowNonDefaultSystemApps.

16.Set it to YES. (If you did this with Meridian Jailbreak, you should do Step 10,11,12 Next to finish up and be on g0blin Again)

17.Save and Close

18.Reboot

**Comment by herman21** [comment]
typing cydia:// in safari does nothing for me

**Comment by Sticktron** [comment]
Steps 13-17, followed by a respring should be enough. might need to run the uicache command too.

**Comment by leart78** [comment]
> DO THIS IF SBShowNonDefaultSystemApps is non existent in : /var/mobile/Library/Preferences/com.apple.springboard.plist
> 
> This worked on my iPad Air 10.3.2, I had to do it up until step 12.
> 
> Writing this so anyone else who has this problem doesn't struggle and loses their mind trying to fix it. lol
> 
> 1.Download g0blin and Meridian
> 
> 2.Jailbreak with g0blin (See Step 8th)
> 
> 3.Open Cydia through Safari with cydia://
> 
> 4.Go install Filza File Manager
> 
> 5.Reboot Tablet
> 
> 6.Jailbreak with Meridian
> 
> 7.Reboot
> 
> 8.You should see Cydia and Filza on the spring board
> 
> 9.If you don't see the icons, Open Filza and do rest of the steps after (Step 13) if Filza Crashes and doesn't open continue with step 10)
> 
> 10.If You Don't/Do see them, Remove Cyida and Meridian.
> 
> 11.Reboot
> 
> 12.Jailbreak with g0blin with FORCE Re-install Bootstrap (Stop here if your icons showed up, like mine which already did)
> 
> 13.Open Filza through Safari with filza://
> 
> 14.Go to /var/mobile/Library/Preferences/com.apple.springboard.plist
> 
> 15.Open the File and find SBShowNonDefaultSystemApps.
> 
> 16.Set it to YES. (If you did this with Meridian Jailbreak, you should do Step 10,11,12 Next to finish up and be on g0blin Again)
> 
> 17.Save and Close
> 
> 18.Reboot

you're the man, thank you very much

**Comment by Veshurik** [comment]
Hm, SBShowNonDefaultSystemApps shows as YES. But Filza installed IPA still doesn't shown on device until respring.
