### ISSUE TITLE
It worked on my 6s+ 10.3.3. But cydia doesnt show up ipad air1 10.3.2

### ISSUE THREAD

**Issue by viddy135** [Sticktron/g0blin#103]
I had xpreeks edition then moved to ur rc0 which was messed up lol. On rc1 i had to open cydia right after jailbreak succeeded and install cydia substrate then it resprang. For my ipad it succeeds but cydia can only be opened thru safari

**Comment by byt3d3lux3** [comment]
Its a known issue and you're not alone (i have to and its kinda annoying lol)

**Comment by viddy135** [comment]
Oh ya ik i mostly wanted to tell him it works 6s+ 10.3.3

**Comment by Sticktron** [comment]
#92
