### ISSUE TITLE
Cydia not appearing when jailbroken Ipad mini 2 ios 10.3.1

### ISSUE THREAD

**Issue by herman21** [Sticktron/g0blin#104]

**Comment by ringosham** [comment]
Not just cydia. All tweak icons are not showing.

**Comment by rnavalgund** [comment]
Hey! If you have blobs for your iPadmini2 for iOS 10.2.1 then downgrade to 10.2.1 because 10.2.1 is much better and has better success rate (jb's work charming on my mini2 10.2.1)

**Comment by byt3d3lux3** [comment]
You will have to go into safari and type cydia:// to enter in Cydia for now. Also when you install tweaked apps for example appcake, you will have to type appcake://

**Comment by ringosham** [comment]
Alternatively, you can install any launcher tweak through cydia:// and add your jailbreak apps there.

**Comment by herman21** [comment]
@ringosham yeah I found that out aswell but nothing opens lol

**Comment by Sticktron** [comment]
#92
