### ISSUE TITLE
Cydia white screen crashing fix

### ISSUE THREAD

**Issue by wahlmanj** [Sticktron/g0blin#107]
I had this issue on my mini 2 on iOS 10.3.1 and fixed it by doing this via ssh. I would assume this would fix cydia on any device having white screen errors.

ssh into device like this if using a Mac:

ssh root@x.x.x.x -p 2222

replace the x.x.x.x with your IP address. Then paste this into terminal:

`cd  /var/mobile/Library/Caches; rm -r com.saurik.Cydia; cd /var/mobile/Library/Cydia; rm -r metadata.cb0`

After that relaunch cydia

It would be a good idea to also change your password by typing passwd. Enjoy ;)

**Comment by Sticktron** [comment]
this would be better as a post on reddit
