### ISSUE TITLE
Tumblr app stuck in safe mode

### ISSUE THREAD

**Issue by DirkT86** [Sticktron/g0blin#108]

**Comment by DirkT86** [comment]
Everything works fine for me with this jailbreak but the Tumblr app gets stuck in safe mode and no matter what tricks I have tried (Reinstalling,Turning on and off, ETC).  If I reboot in non jailbroken mode it works fine so it's not really an issue for me, Just pointing out a noticed bug

**Comment by Emu1342** [comment]
Having this issue too. I thought I was going crazy

**Comment by DirkT86** [comment]
I went on the web browser version and it kept turning itself back on after I would turn it off!  After turning it off maybe 20+ times in the web browser the app started working again no problems lol. I don't know if that was what fixed it but you could give it a shot lol

**Comment by edicks2481** [comment]
Same here; It's a little annoying!
(iPhone 6 Plus, 10.3.3)

**Comment by Sticktron** [comment]
Moved to #241
