### ISSUE TITLE
iPhone 5s 10.3.3 jailbreak works fine

### ISSUE THREAD

**Issue by gr8den** [Sticktron/g0blin#110]
I have jailbroken my iPhone 5s 10.3.3 with RC1. Touch ID in applications from App Store also works. Please update README.md

**Comment by peco77** [comment]
Everything works fine on my iPhone 6s 10.3.3 as well. Running stable for more than 2 days.

**Comment by count-0** [comment]
I can also confirm that iPhone 5s (iPhone6,1) works with RC1. I am on 10.3.3 as well.

**Comment by burhangee** [comment]
I can confirm too. Working both on iPhone 5s 10.3.3 and iPhone SE 10.3. Just jail-broken both. Cant say how stable but it is working good . Thanks Sticktron.

**Comment by Sticktron** [comment]
thank you
