### ISSUE TITLE
VPN Not working after Jailbreak

### ISSUE THREAD

**Issue by KingMczjk** [Sticktron/g0blin#112]
When I Jailbreak my phone and try use a VPN app to give my phone a VPN it doesn't work, but when I reboot my device (losing jailbreak) it works. Please fix

**Comment by 815807765** [comment]
设置好VPN再越狱就好了

**Comment by drewgreen** [comment]
@KingMczjk I have a 6s 10.3.1 no issues with TorGuard or OpenVPN

**Comment by webmanjonny** [comment]
@KingMczjk I have a 6s 10.3.1 no issues with TorGuard or OpenVPN

**Comment by KingMczjk** [comment]
Problem Solved.
