### ISSUE TITLE
remove jailbreak from g0blin beta

### ISSUE THREAD

**Issue by AbdelHakim75** [Sticktron/g0blin#115]
Please how to remove jailbreak from g0blin beta to install g0blin RC1

**Comment by W3ddl3Q5** [comment]
You can try by using cydia impactor and install the new ipa. It should overwrite the ipa

**Comment by AbdelHakim75** [comment]
I did but when I'm in the RC1 application it jailbreak not my iphone

**Comment by Sticktron** [comment]
The official releases will automatically upgrade you. As long as the beta you tried wasn't corrupted by someone else.
