### ISSUE TITLE
unknow battery drain on iphone 6s 10.3.1

### ISSUE THREAD

**Issue by kurodaxx** [Sticktron/g0blin#116]
the jailbreak seem to be stable, i love it, but it seem like the battery is drainning too much. I try to oversee the battery and i can't find the problem. The battery usually normal after i delete tweak, and after i think i find the problem, the battery seem to drain again. It keep happend, even i uninstall all the tweak already.  the only thing i find unusual is com.apple.springboard.
![26992105_2057204847628074_8994684358705955366_n](https://user-images.githubusercontent.com/35522724/35033902-e6fd01d2-fb9e-11e7-97e8-b2c9ee486198.jpg)

**Comment by Sticktron** [comment]
Battery drain from SpringBoard is most likely due to a tweak.
