### ISSUE TITLE
Reboots when jailbreak is successful

### ISSUE THREAD

**Issue by frankthedead** [Sticktron/g0blin#12]
I got working on first time, installed some tweaks to test. On second try, instead of only respring springboard it reboots into non-jailbreak mode.

**Comment by zawata** [comment]
I'm experiencing the same issue. 

I've narrowed it down to line 4 of the reload script where it unloads all of the launch daemons. I think that unloading one those daemons is rebooting the phone but I don't know enough about iOS to say thats the cause or even know which of the daemons shouldn't be unloaded.

I can unloadindividual daemons without a reboot which leads me to believe that it's one of the 288  it auto-unloads.

**Comment by Danoded** [comment]
Cydia installed for you guys right? Tried uicache and killall -9 SpringBoard but it still doesn't appear.

**Comment by Sticktron** [comment]
@zawata I modified the reload script so that launch daemons are no longer unloaded, that should help for now.

**Comment by frankthedead** [comment]
Well, I create a new issue but I could just say it here. It's not fixed yet, tried but still reboots.
