### ISSUE TITLE
G0blin won't install cydia. Iphone6s+ jailbreaks but lack of Cydia

### ISSUE THREAD

**Issue by xkassab** [Sticktron/g0blin#122]

**Comment by DirkT86** [comment]
Open safari and type the in your search bar 

Cydia://

Hopefully it'll work for you until the bugs are sorted!

**Comment by xkassab** [comment]
"Safari cannot open the page because the adress is invalid." but g0blin says "Jailbreak yo"

**Comment by DirkT86** [comment]
Too bad :(  maybe try re-booting you phone and re side load goblin!  I think there is some info on this topic out there as well so check out some forums and the other threads on here.  Someone might have a work around for you

**Comment by xkassab** [comment]
Can I just do an erase all on my phone?

**Comment by DirkT86** [comment]
If you're talking about erase all in the settings app I wouldn't suggest it!

**Comment by Sticktron** [comment]
#92
