### ISSUE TITLE
Apps do not load configuration after jailbreak

### ISSUE THREAD

**Issue by fox34** [Sticktron/g0blin#123]
iPhone 5s, 10.3.1. Most things are working fine in jailbroken state:

- In-App TouchID for **some** Apps, tested with 1Password, not working with Outbank
- Cydia shows up
- Respring button worked at all times for me
- No battery issues so far
- No GPS issues

However, some apps "forget" all stored settings while jailbroken. In a quick test, at least reddit and Feedly were affected. You can then change settings. After rebooting to a non-jailbroken state, the default configuration was back as normal. After a re-jailbreak, the "jailbreak configuration" is back.

Installed packages: Activator (beta), DetailedBatteryUsage, Filza, FlipControlCenter, Protect My Privacy, Speed Intensifier.

**Comment by webmanjonny** [comment]
I'm experiencing the same symptoms iphone 6s 10.3.1

**Comment by GeekBreak** [comment]
Same, i6S 10.3.1, had to login again in almost every app

**Comment by Sticktron** [comment]
I can confirm

**Comment by burhangee** [comment]
Same issue , the VEON app that is liked to my carrier fails to retain settings. iPhone SE, 10.3

**Comment by Sticktron** [comment]
moved to #181
