### ISSUE TITLE
Random reboots

### ISSUE THREAD

**Issue by sooperaya** [Sticktron/g0blin#124]
device will automatically reboot sometimes (rarely) and will have to jailbreak again

**Comment by webmanjonny** [comment]
I'm pretty sure thats normal mate..

**Comment by Sticktron** [comment]
Definitely not normal. I haven't had any spontaneous reboots yet. I'm hoping this might be tweak related?

**Comment by webmanjonny** [comment]
Sorry I stand corrected. The god has spoken! Thank you @Sticktron !!

**Comment by viddy135** [comment]
Nope can confirm, just happen on my 6s+ and then everytime i try to respring either by bug or cydia just reboots. Happen 5 times till it resprang into jailbroken state

**Comment by webmanjonny** [comment]
@viddy135 are you saying your device reboots when tapping onto the 'respring' button? If so, thats a known bug - https://github.com/Sticktron/g0blin/issues/94

**Comment by viddy135** [comment]
Nope after jailbreaks i try to force respring by other means and it still rebooted

**Comment by Sticktron** [comment]
@viddy135 yeah that's a different issue (#94). This one is about spontaneous reboots. The other one is about a reboot triggered by respringing.

**Comment by viddy135** [comment]
My bad im not explaining properly. So my ip6s+ 10.3.3 randomly rebooted. Whenever i tried to respring using cydia and reinstalling a tweak, it would reboot instead. Same thing with the spotlight glitch. It finally worked on the 4 or 5th try

**Comment by Sticktron** [comment]
#94
