### ISSUE TITLE
Battery drain (Camera Audio)

### ISSUE THREAD

**Issue by Peeprince** [Sticktron/g0blin#127]
Unfortunately I still had Camera Audio battery drain up to 40%. I checked force reinstall bootstrap of course, and I have location off all the time. How could it be fixed?

**Comment by yur1xpp** [comment]
Duplicate issue #83

**Comment by Peeprince** [comment]
Also phone audio drains quite much even the phone app isnt used. scary.

**Comment by Sticktron** [comment]
#83
