### ISSUE TITLE
iMessage App (Game - Checkmate!) not working with g0blin active.

### ISSUE THREAD

**Issue by D-an-W** [Sticktron/g0blin#128]
Hi folks,

I just wanted to report that g0blin appears to affect iMessage apps, specifically here the Chess game "Checkmate!"

After a reboot, before reactivating g0blin it works ok but once jailbroken the game doesn't load, has anyone else tested other iMessage Apps?

**Comment by parrotgeek1** [comment]
This smells of sandboxing issues

**Comment by Sticktron** [comment]
Moved to #241
