### ISSUE TITLE
DOCK CONNECTOR ISSUES

### ISSUE THREAD

**Issue by zcustodio27** [Sticktron/g0blin#131]
Constant dock connector issues only when jailbroken, and does not happen after reboot. Constantly disconnection and reconnection only when jailbroken on 10.3.1 iPhone 6 plus. Not a hardware issue  either brand new wire and lighting port is fine.

**Comment by DragonSlayerDx** [comment]
Have you tried to rejailbreak? This happens to me sometimes even before i jailbroken so it might be the Phone it self

**Comment by zcustodio27** [comment]
Phone is fine when not jailbroken and only has connection issue when in jailbroken state, wire is brand new from apple.  I have to reboot or it will just constantly connect in reconnect only when jailbroken.

**Comment by zcustodio27** [comment]
This happens when trying to play music with my cars dock connector only.

**Comment by zcustodio27** [comment]
Issues still occur in RC2 when the jailbreak is active.

**Comment by kayfwee** [comment]
+1 to this issue, experiencing it when trying to play music over USB in a car. Using RC2 on 10.3.2.

- Only plays the first song in alphabetical order
- Trying to play a different song by selecting it on my phone doesn't work, instantly overrides back to the first song
- Album art and song progress does not display on the car's infotainment screen
- Can see the full list of songs on my phone through the car's infotainment screen, but selecting them doesn't do anything
- Playing through Bluetooth still works so I'm using that as a temporary workaround, although would much prefer playing over USB

**Comment by zcustodio27** [comment]
Every issue he is having I am having ass well on both RC1 and RC2

**Comment by Sticktron** [comment]
I believe this is related to the same issue that causes other authentication issues (eg TouchID, Settings not saving, etc.)
