### ISSUE TITLE
Sideloaded apps crash on launch when rebooting after a successful jailbreak

### ISSUE THREAD

**Issue by GeneralCuster** [Sticktron/g0blin#137]
It seems as though the signatures of all side-loaded apps (including g0blin) become invalid after the device is restarted after being put into a jailbroken state, with a successful respring.

It doesn't seem to happen if the device is jailbroken, but not resprung, as I can still use the g0blin app if it reboots the phone on the first respring.

It's very unfortunate because it basically turns this into a tethered jailbreak as I have to reinstall the app everytime I reboot my phone :(

I'm using my developer account to sign the apps, maybe that has something to do with it?

**Comment by DragonSlayerDx** [comment]
Perhaps you could try Immortal?

**Comment by cameron7410** [comment]
That happened to me until I uninstalled immortal and then they opened up.

**Comment by GeneralCuster** [comment]
Thanks cameron7410, that was it!
