### ISSUE TITLE
Unable to receive AirDrop

### ISSUE THREAD

**Issue by holddownshift** [Sticktron/g0blin#138]
My device: SE 10.3.2 RC1

Unable to receive AirDrop regardless of jailbreak state

Outputs "AirDrop Failed" notification on receiving end, shows "Failed" status on AirDrop menu in sending device

Might be related to issue regarding DRM file failure in apps

**Comment by D-an-W** [comment]
I tested this on my 6S+ yesterday and could both send and receive with g0blin enabled.

**Comment by holddownshift** [comment]
Tested on other devices, works fine. May be a one-time thing. Closing Issue.
