### ISSUE TITLE
iPhone gets disabled if jailbroken

### ISSUE THREAD

**Issue by antoniu200** [Sticktron/g0blin#142]
Hi! So a couple of minutes ago, while I was screwing around with AdvancedSettings8, after a respring, the message "iPhone is disabled" message appeared. I'm running iOS 10.3.1 on iPhone 5s. Why is this? BTW, after I reboot the device and I don't jailbreak it, I can use it without a problem, no disabled shit. Can you help?

EDIT: I can use the jailbreak if I don't respring.

**Comment by GeneralCuster** [comment]
Try force-reinstalling the bootstrap the next time you run g0blin.  That should remove any tweaks, theoretically allowing you to jailbreak anew.

**Comment by antoniu200** [comment]
That would have done it, g0blin is a well thought jailbreak. But I solved it by SSH into iPhone and deleting AdvancedSettings8's .plist files. Sorry for the lost time, I was tired last night (when this thread was opened) and I didn't want to think about it. But I had to, afterall this 5S is my main device.
