### ISSUE TITLE
Doesn't work iPhone SE iOS 10.3.1 Cydia not installed or crash after install

### ISSUE THREAD

**Issue by cyberfunk** [Sticktron/g0blin#143]
I can't get this to work... At first I could not even get Cydia installed. Then after multiple tries and Cydia installed it just crashes on launch. I've tried everything including force re-installing Bootstrap waiting 20 seconds, shut down and re-install and absolutely nothing. Yalu for 10.2 on my iPhone SE is a breeze but G0blin is a no go for me. Any tips are MUCH appreciated as this will be my sister's first Jailbroken device:-)

**Comment by Sticktron** [comment]
try RC2
