### ISSUE TITLE
G0blin force closes 

### ISSUE THREAD

**Issue by hawaiianstudd** [Sticktron/g0blin#144]
Both times was after a week of being  jailbroke. My phone would reboot and after clicking g0blin app it immediately force closed. No longer have the profile in settings and unable to open g0blin. Is this suppose to happen after a week?

**Comment by Sticktron** [comment]
Yes. Persona signing certificates only last 7 days, then you have to re-sign using Impactor.

Ext3nder is another option to auto-renew the signature for you.
