### ISSUE TITLE
Help guys 

### ISSUE THREAD

**Issue by DragonSlayerDx** [Sticktron/g0blin#147]
I know this is off topic but I found out that my iPad was have springboard crashing because I restored data from my previously jailbroken ios 10.2 ( now on 10.3.1 ) when I got a boot loop , so I decided to restore to 10.3.1 which was the only signed ios at that time and then restore iCloud. A year later G0blin came so I used it then I got the issue , Is there anything at all I can do to get rid of this problem without losing iCloud data ? Thanks

**Comment by Sticktron** [comment]
try posting on reddit/r/jailbreak
