### ISSUE TITLE
iPhone SE 10.3.2 jailbreak not work fine

### ISSUE THREAD

**Issue by Investegate** [Sticktron/g0blin#148]
Hi,
their are a few problems.

When i install it with the impactor i get at the end a error, but the jailbreak is installed..:
![error](https://user-images.githubusercontent.com/35893945/35483050-97afe7f0-043d-11e8-8b6c-6808c8ea7e8b.PNG)

After a few times by pressing the jailbreak button and a few resprings, it works. 
But if i do a restart, the jailbreak is gone and it only works agian after many time of trying to jailbreak again and after more than 20 resprings.

**Comment by Sticktron** [comment]
expected behaviour.
