### ISSUE TITLE
你好 6s 10.3.1 无法使用rc2工作）（无法激活越狱状态）   我只能再次使用rc1 重新激活越狱

### ISSUE THREAD

**Issue by Obsession-Alvin** [Sticktron/g0blin#152]

**Comment by Obsession-Alvin** [comment]
Hello 6S 10.3.1 can't work with RC2) (unable to activate jailbreak state) I can only use RC1 again to reactivate the prison break

**Comment by iAppleLuvr** [comment]
然后使用rc1 

lol google translate

**Comment by ringosham** [comment]
Please use English next time.
The title says "iPhone 6s doesn't work on rc2 in iOS 10.3.1 (Cannot be jailbroken) My only choice is to use rc1"
