### ISSUE TITLE
RC2 Not working with iPad 5 (2017, A9 64bit chip)

### ISSUE THREAD

**Issue by ridwan47** [Sticktron/g0blin#155]
Tried so many times. It reboots but doesn't install cydia. Doesn't jailbreak. :(

**Comment by ridwan47** [comment]
iOS 10.3.1 btw

**Comment by ridwan47** [comment]
RC1 doesn't work either.

**Comment by Sticktron** [comment]
To un-hide the Cydia icon see this workaround: #186

**Comment by ridwan47** [comment]
it doesn't jailbreak in the first place :(
