### ISSUE TITLE
Tweaks not loading until respring in jailbroken mode again.

### ISSUE THREAD

**Issue by arinc9** [Sticktron/g0blin#156]

**Comment by Sticktron** [comment]
that's how it's supposed to work.

**Comment by arinc9** [comment]
I know but it happens so rarely. But I regret posting here because it's something to do with 0.reload.plist which has nothing do to with your project. Thanks anyway.

**Comment by arinc9** [comment]
I'd like to help but I don't know which tools can help me debug this.
