### ISSUE TITLE
iPhone SE running 10.3.2

### ISSUE THREAD

**Issue by ghost** [Sticktron/g0blin#160]
Hi Sticktron, everytime I download g0blin ipa, it installs fine, but when I click on the application it won't open, meaning I cannot jailbreak:( anyways thanks for providing us a jailbreak:)

**Comment by DirkT86** [comment]
You have to go to settings/general/device management and trust the certificate for the app after you first install it

**Comment by RikGissel** [comment]
DirkT86 I already did that, but it still doesn't open the app when I tap it.

**Comment by DirkT86** [comment]
Did you try deleting it and resideloading it?  Maybe even download G0blin again just to be safe!  Also check impactor for updates
