### ISSUE TITLE
RC2 not working on iPhone 6 iOS 10.3.3

### ISSUE THREAD

**Issue by makwanbk** [Sticktron/g0blin#162]
After pressing Jailbreak button , rebooted the device

**Comment by dodo634** [comment]
work for me - Iphone 6 ios 10.3.3 (14G60)

**Comment by DirkT86** [comment]
You have to try to jailbreak it multiple times still!  This update is supposed to fix the respring issue after you're done jailbreaking

**Comment by dodo634** [comment]
everything worked for me the first time
