### ISSUE TITLE
G0blin RC1 & RC2 after jb, the Notes app to lock/unlock notes do not respond.

### ISSUE THREAD

**Issue by itsyasso** [Sticktron/g0blin#163]
G0blin RC1 & RC2 after jb, the Notes app to lock/unlock notes do not respond.

**Comment by D-an-W** [comment]
I can open a locked Note once by manually entering its password (No Touch ID) but it won't let me open it a second time, pressing "View Note" has no response the second time a locked Note is opened.

g0blin RC2 on iPhone 6s Plus

**Comment by Sticktron** [comment]
Moved to #241
