### ISSUE TITLE
Apple Watch Issue

### ISSUE THREAD

**Issue by Emu1342** [Sticktron/g0blin#167]
Series 2 Watch OS 3.2.2 Music app does not seem to communicate with phone correctly.

• Does not show now playing songs
• Can not skip track
• Can not go to previous track

Photo shows phone and watch displaying different songs. Shows greyed out next/previous buttons.

![img_1403](https://user-images.githubusercontent.com/35937531/35534679-3f7eac10-050f-11e8-868d-b564e4930b19.PNG)
![img_1404](https://user-images.githubusercontent.com/35937531/35534683-43e4febc-050f-11e8-941d-f5000a719cb3.PNG)

**Comment by Sticktron** [comment]
possibly related to #84,  #109, #128, #181

**Comment by Sticktron** [comment]
Moved to #241
