### ISSUE TITLE
Will not force re-install bootstrap. RC1. iPhone 6. iOS 10.3.3

### ISSUE THREAD

**Issue by User395439** [Sticktron/g0blin#168]
Previously installed tweaks and rebooted, but can't remember which one caused it.
Upon re-jailbreaking, the device resprings and says its jailbroken but it is not. Most tweaks are completely uninstalled and some sources are gone. Can install tweaks but they don't work.
Inside g0blin RC1, the force re-install toggle won't stay toggled and inside g0blin RC2, re-install Cydia toggle won't stay toggled and won't reactivate the jailbreak at all. 
This is on iPhone 6 running iOS 10.3.3 with g0blin RC1.
Demo:
[https://www.youtube.com/watch?v=um5o1tYc2oY](url)
(If link doesn't work, search "Asa Frye" in YouTube search and find video named "g0blin RC1 Jailbreak Activation Defect"

**Comment by Sticktron** [comment]
The toggle resets to the off position when you re-open the setting page by design. You really aren't supposed to be re-installing the bootstrap. In fact I've just decided I'm going to remove the option in RC3

**Comment by User395439** [comment]
Ok, thanks. I'm not very knowledgeable in jailbreaking, obviously. I've just seen people do it, saying it's a good idea without knowing what it means. All I know how to do is install Cydia and install tweaks and that's basically it. I really need an education.
