### ISSUE TITLE
This jailbreak doesn't work for me 

### ISSUE THREAD

**Issue by TumblrGotMeLaid** [Sticktron/g0blin#170]
Idk why it installs goblin and cydia but cydia will never open .. it always crashes no matter how many times I try hitting jailbreak or re doing the whole thing over

**Comment by Sticktron** [comment]
what device and OS version?

**Comment by TumblrGotMeLaid** [comment]
It's iOS 10.3.3 iPhone 6s Plus , lol I know how to jailbreak just fine .
I've been jail breaking ever since the iPhone 4 and I always find a way to
fix it but this jialbreak stresses me out lol it works sometimes and it
stays jailbrokem for about 4 days then one day restarts and does this ..

**Comment by Sticktron** [comment]
If you were able to jailbreak with g0blin, then g0blin did it's job. Maybe the problem is something else you installed.
