### ISSUE TITLE
RC1 & RC2 Not working 10.3.3 iPad Pro 

### ISSUE THREAD

**Issue by OneCruelSOB** [Sticktron/g0blin#177]
RC1 start to jailbreak but will not Respring to finish. RC2  just reboots after pressing the jailbreak button. It's a 13" iPad Pro 10.3.3

**Comment by haidang1904** [comment]
remove current G0blin version.
restart your phone.
install again G0blin RC2.
press jailbreak again. maybe, you should try again/restart many time to get jailbreaked.
goodluck

**Comment by OneCruelSOB** [comment]
I have all ready tried that and it still does not work. I have been using jailbreaks since the 1st gen iPhone so I know how hard it can be and some can be really easy. This g0blin jailbreak just does not work for this type of iPad on iOS 10.3.3.

**Comment by JBDaz** [comment]
RC2 DOES work on ipad Pro 12.9" 10.3.3 - using it myself. (see my issue #181 though ...)

**Comment by OneCruelSOB** [comment]
Ok well it does not work on my iPad Pro 13" 10.3.3 (WI-FI) I have uninstalled reinstalled it 3 to 4 different times I have tried it about 50 times and it just rebooted the iPad but at first it will fail then I wait a minute and then press jailbreak and it just reboot the iPad.  I have deleted all settings and reinstall just RC2  same thing happens I have put it in airplane mode pressed jailbreak same thing happens. So I don't know what's going on all I can say is it might work on some Apple products but not all

**Comment by OneCruelSOB** [comment]
OK after about 40 or 50 times I have finally got it to install I don't know what was going on they give me the error after install and Cydia I did have to install a ifunbox  to fix the Cydia loading problem after you said you had it working on yours I figured I would give it a few more tries but it did work and does work on ISO 10.3.3 iPad Pro 13 inch Wi-Fi version. Thank you for your quick response I appreciate it

**Comment by Sticktron** [comment]
If the app says you are jailbroken but you don't see Cydia that is because a new setting failed to write to SpringBoard's preferences file.

If that setting is missing, SpringBoard will hide the icons of any apps installed to the /Applications folder.

To fix it for now you can set it yourself, using Filza.

File: `/User/Library/Preferences/com.apple.springboard.plist`
Key: ` SBShowNonDefaultSystemApps`
Type: `Boolean`
Value: `YES`
