### ISSUE TITLE
RC2 (paid) appstore-apps ignore settings from settings app

### ISSUE THREAD

**Issue by JBDaz** [Sticktron/g0blin#181]
(iPad Pro 12.9 1st Gen / 10.3.3.) - g0blin RC2

Apps from the appstore work but ignore their settings from the settings app while jailbroken.
Re-installing them while jailbroken does not help.
It looks like apps have no permission to access the settings ?

All is fine when returning to an un-jailbroken state.

**Comment by Sticktron** [comment]
Moved to #241
