### ISSUE TITLE
HELP, ALL IS MISSING

### ISSUE THREAD

**Issue by leung991085** [Sticktron/g0blin#183]
All the icon,  settings,  Cydia are missing....
I can install g0lib using Cydia Impactor but not helpig
I don't know how to fix it..
https://imgur.com/a/Kq3Mv

It is Ipad Air

**Comment by Sticktron** [comment]
Please use http://reddit.com/r/jailbreak for troubleshooting issues not related to g0blin itself.

**Comment by leung991085** [comment]
Thanks,  I though it is the cause of using Cydia to respring instead of using g0blin
