### ISSUE TITLE
DOESNT WORK

### ISSUE THREAD

**Issue by Devang1** [Sticktron/g0blin#19]
iphone 6s ios 10.3.3 doesn't work.![Image](https://i.imgur.com/2YUpG3C.jpg)

**Comment by Danoded** [comment]
Because it doesn't have 6s, 10.3.3 offsets...

**Comment by frankthedead** [comment]
L - O - L

**Comment by Devang1** [comment]
when will offsets be added for my device?

**Comment by djmuted** [comment]
@Devang1 get them here https://github.com/thisiswisy/v0rtex-injector/blob/master/v0rtex-S/symbols.m

**Comment by Devang1** [comment]
i didn't compile the ipa myself. i can't do so because i don't own a mac. would you mind compiling it for me? id really appreciate it.

**Comment by zawata** [comment]
Yeah this needs to be closed. Literally not helping at all.
