### ISSUE TITLE
RC2 G0bline

### ISSUE THREAD

**Issue by vikassaroha84** [Sticktron/g0blin#193]
many time click jailbreak but nothing happen every-time phone restart what we do now my IOS is 10.3.3 iphone 6s

**Comment by vikassaroha84** [comment]
kernel panic and phone restart every time i was try approx 50 times but issue is same previously its working fine

**Comment by vikassaroha84** [comment]
RC1 is working fine but RC2 not working every time kernel panic and restart phone

**Comment by rohit5233** [comment]
rc2 bad not work 20 times restart phone but not jailbreak

**Comment by nik312123** [comment]
The same problem happened to me, too, but I already opened an issue on this. (See #189) I think that you should post your agreement in #189 and close this duplicate issue.

**Comment by lexieye** [comment]
N69uAP (14E304)
g0blin Rc1 & Rc2 = device not supported!
G0blin "by xPeeks" ipa only one that works?

I want to reinstall Cydia as I have broke the signed state & it crashes trying to open.  Pls can you look into adding SE 10.3.1 support

**Comment by Sticktron** [comment]
#117
