### ISSUE TITLE
Cydia not working

### ISSUE THREAD

**Issue by DragonSlayerDx** [Sticktron/g0blin#194]
''flAbsPath on /var/lib/dpkg/status failed - realpath (2; No such file or directory)
Could not open file - open (2; No such file or directory)
Problem opening'' it appears on cydia when first opened
this is the problem i have had with RC2 .(ipad mini 2 , ios 10.3.1 completely reset to new )

**Comment by DragonSlayerDx** [comment]
Nevermind i solved it lol

**Comment by nik312123** [comment]
Please close the issue if it no longer exists. Additionally, if you wish, tell us what caused the problem in the first place and fixed it, and then close the issue.

**Comment by Sticktron** [comment]
doesn't seem like they're going to respond. closing.
