### ISSUE TITLE
g0blin crashes if there's no internet connection

### ISSUE THREAD

**Issue by GeekBreak** [Sticktron/g0blin#197]
As title says, g0blin crashes if there's no internet connection, already seen this issue with other v0rtex-based app like v0rtex-injector, so I don't know if this is "expected".

Device: iPhone 6S (N71mAP)
iOS Version: 10.3.1
g0blin Version: RC2 (also happens with older ones)

**Comment by Sticktron** [comment]
I can't reproduce this.

**Comment by GeekBreak** [comment]
https://www.dropbox.com/s/5ly8vo7g1bda6j9/g0blin_crash.mp4?dl=0

**Comment by GeekBreak** [comment]
fixed in preRC3
