### ISSUE TITLE
iPad 6 10.3.1 jailbreak working with RC1 not with RC2

### ISSUE THREAD

**Issue by dinjojo** [Sticktron/g0blin#203]
Multiple reboots really tired now can it be cleaned up in RC3

**Comment by DragonSlayerDx** [comment]
Whats an ipad 6?

**Comment by dinjojo** [comment]
iPad 2017

**Comment by Sticktron** [comment]
The 2017 iPad (also known as the iPad 5th generation, even though it's the 7th generation) is supported, and I have heard from other users that it does in fact work.
