### ISSUE TITLE
Cydia crash within opening

### ISSUE THREAD

**Issue by zsayen** [Sticktron/g0blin#204]
I'm not sure what the problem is I'm running iOS 10.3.1 iPad mini 4, my tweaks work but cydia doesn't it doesn't make sense. Can you help?

**Comment by zsayen** [comment]
I think it might be something to do with Filza

**Comment by xxHoBoZxx** [comment]
Did you happen to install xcon? It is known to break Cydia

**Comment by zsayen** [comment]
Thank you so much

**Comment by zsayen** [comment]
Fixed

**Comment by nik312123** [comment]
Please subsequently close this issue then.

**Comment by Sticktron** [comment]
Removing xcon fixed issue.
