### ISSUE TITLE
iPhone 6 restarts 

### ISSUE THREAD

**Issue by ztwen3** [Sticktron/g0blin#205]
Went I click in jailbreak it will restart and no jailbreak every time

**Comment by dodo634** [comment]
the first time everything had worked but for some time I have reboot when i want to jailbreak

**Comment by DaveFlash** [comment]
had the same problem, but the fix was waiting for atleast 60-90 seconds after opening the g0blin app before tapping the jailbreak button.. also patience is your friend. and it might fail even then, so give it multiple tries...

**Comment by ztwen3** [comment]
Also when I re jailbreak I should install all Tools in cydia
There is any solution for this issue

**Comment by Sticktron** [comment]
Just keep trying. Sometimes it helps to wait 30s after rebooting before trying again.
Once you get back into jailbroken mode your tweaks will be still there.
