### ISSUE TITLE
IPhone 6 ios 10.3.3 cydia crashes

### ISSUE THREAD

**Issue by xPirateKingx** [Sticktron/g0blin#21]
jailbreak works but cydia doesn't open at all rebooted many time and re jailbreak but doesn't open crashes after 5 to 6 seconds though you can install ifile ipa from pc or any other website like app valley to get root access!

**Comment by WitchSn0w** [comment]
Same thing for me. I have an iPhone 6 with ios 10.3.3, the jailbreak has been successful but cydia crasha after about ten seconds. With iFile installed by AppValley I have root permissions.
I look forward to news and improvements.
Thank you for what you do in the community.

**Comment by xPirateKingx** [comment]
no problem bro

**Comment by Sticktron** [comment]
not applicable to RC0
