### ISSUE TITLE
Tweaks list

### ISSUE THREAD

**Issue by DedoGamingONE** [Sticktron/g0blin#210]
Hi i need to know what tweaks work on the g0blin rc2 because i want to install anemone and some themes but i dont want to brick my phone again

**Comment by nik312123** [comment]
Anemone doesn't work yet for iOS 10.3.3. Here is a decent list of working tweaks: https://docs.google.com/spreadsheets/d/1r9jSb2-WuwnEC6nIxdJRdgaxhj6SrNJgER9JnVQwWn0/edit#gid=0

**Comment by patelarpit50** [comment]
So now anemone work ???

**Comment by nik312123** [comment]
No... This was closed because this is an Anemone issue, not a g0blin issue.

**Comment by patelarpit50** [comment]
Okay thanks
