### ISSUE TITLE
restart every time

### ISSUE THREAD

**Issue by lhhfate** [Sticktron/g0blin#211]
iphone se 10.3.1
Went I click in jailbreak it will restart and no jailbreak every time

**Comment by nraiha** [comment]
I have had the same problem. When your phone restarts, shut all the apps, clear the ram (hold sleep button 'till the shutdown option comes, then hold home button until your phone returns to springboard) and let it be for a while (~10min). Then try it

**Comment by lvminia** [comment]
Worked for me thanks ! (even without waiting 10mins)
