### ISSUE TITLE
issue g0blin jailbreak not respringing keeps hanging on finishing and installed dropbear.

### ISSUE THREAD

**Issue by minefreaky** [Sticktron/g0blin#215]
Dear stickton i finaly found someone who could add offset for ipad air 2 (14G5053A) but when i try to jailbreak it does it goes on but keeps hanging at finishing at installed dropbear it doesnt respring.
and theres no cydia anywhere i tried the (cydia://)

![img_2498](https://user-images.githubusercontent.com/35143397/35760682-2812efc0-0882-11e8-826f-30cf433ddb2b.PNG)

**Comment by Sticktron** [comment]
They have changed the code somehow (I can tell because there is no dropbear installed by RC2). They might have made a mistake somewhere.

If you send me the offsets I can add them to g0blin officially.
