### ISSUE TITLE
No Cydia

### ISSUE THREAD

**Issue by Sakura20** [Sticktron/g0blin#216]
So I got the the g0blin .ipa installed on my iPad Air (Wifi) ios 10.3.3, but while installing using Cydia Impactor it was stuck on "generating application map", there was only a little bit left til that part was complete but it got stuck when it was almost done. Someone told me that I can still able to trust & launch the app. I tried to do that, trusted the app and launch it and it said that it was jailbroken, but I look everywhere on my ipad but I don't see Cydia anywhere. Please help!

**Comment by JohnnieMin** [comment]
did you solve this problem?

same here..
