### ISSUE TITLE
RC2 Worse than ever

### ISSUE THREAD

**Issue by JBL1503** [Sticktron/g0blin#219]
Installed RC2. Got it to Jailbreak once out of about 50 attempts,  No good.   Then when I did get it to jailbreak, I cannot SSH into file structure.  Fucking shit.  Yes I got the Cydia icon now, but reverting back to RC1, since this is more bugged than ever.  

Also never finishing. Just stick on 'generatingApplicationmap'

iPad Air 2 running 10.3.1.

**Comment by nraiha** [comment]
"RC2 uninstalls dropbear for everyone. If you want to use ssh you can install OpenSSH from Cydia."
From the readme.  When jailbreaking, give it some time before pressing the jailbreak button.

**Comment by weiliu423** [comment]
Just to tell anyone what I'm experience by using g0blin jailbreak RC2 on my i6s Plus iOS 10.3.3

The newest way, I found is when you click into g0blin ipa, dont click on jailbreak button yet.

Look at the status of the phone it shows.

1 is CPU and 2 is Ram etc

You only need to look at CPU. 

When the CPU usage is less than 5% then press the jailbreak button. 

It should jailbreak successful to 100% without any fail of reboot or try again message.

Hope it helps.
