### ISSUE TITLE
Cydia never installs

### ISSUE THREAD

**Issue by Danoded** [Sticktron/g0blin#22]
No matter what build. Always try uicache and killall -9 SpringBoard but Cydia never appears, and cannot be accessed via Safari.

**Comment by xNako** [comment]
Force install bootstrap.

**Comment by Danoded** [comment]
Yeah tried that several times, no good.

**Comment by Sticktron** [comment]
not applicable to RC0

**Comment by Danoded** [comment]
Oh sorry forgot to close this issue ages ago.

**Comment by Sticktron** [comment]
No worries.
