### ISSUE TITLE
[Bug] Options from Settings won't effect app itself

### ISSUE THREAD

**Issue by oguzhanvarsak** [Sticktron/g0blin#222]
I just noticed this issue. I am playing a game named VainGlory. It has options like left handed mode or change map position or language on settings. In jailbroken mode, changes not effecting to game. I selected English as game language, but it still working with default language (system language). And for confirm,  i tried on other apps. I just have some options for Tumblr. I tried to disable "safe mode" which blocks mature content. It didn't effect the app too, the app still says "disable safe mode for see this content". After these, i reboot my device and tried again. Every option applied.

**Comment by Sticktron** [comment]
see #181
