### ISSUE TITLE
Cydia startup stuck blank - iP5s

### ISSUE THREAD

**Issue by SametChan** [Sticktron/g0blin#23]
IOS - 10.3.1 from iPhone 5s doesn't work startup Cydia it's stuck blank then back to the home screen.

g0blin apps were said Cydia is enabled and jailbreak completed, then rebooted my phone when startup Cydia is stuck blank.

**Comment by xPirateKingx** [comment]
cydia doesn't work only with lucky people though you can install ifile using appvalley to get root access

**Comment by SametChan** [comment]
Oh, do you have a guide to install for iFile? I have a v0rtex and g0blin right now.

**Comment by WitchSn0w** [comment]
Go to http://appvalley.vip/ with your iPhone and click on "Install AppValley"
Open AppValley search iFile and install it.
iFile in this moment show all directories and you have root access but you can't write/create new file.

**Comment by SametChan** [comment]
@WitchSn0w Thank you!

**Comment by mohammedtabish** [comment]
Yeah same thing Cydia shows white screen and then force closes
Iphone 5s 10.3.2

**Comment by WitchSn0w** [comment]
Look my post " HOW TO FIX CYDIA BLANK SCREEN"

**Comment by mohammedtabish** [comment]
Thanks
