### ISSUE TITLE
Respring never ends/starts

### ISSUE THREAD

**Issue by cppkyle** [Sticktron/g0blin#230]
I have respring progress installed and when I jailbreak, 2/3 of the time the respring bar never moves and after about 20 seconds my screen fades and I can open back up like if it was my home screen. Strangely, the only times my respring works is right after I take the bus. (I live in Canada and its cold here so my device cools down)
![img_5577](https://user-images.githubusercontent.com/33187539/35823678-5aad544a-0a7e-11e8-9f5b-31bb11a1ce19.PNG)

**Comment by Sticktron** [comment]
That is an issue with the tweak. Maybe it hasn't been updated for 10.3?
