### ISSUE TITLE
I found a solution for you guys who have crashing Cydia

### ISSUE THREAD

**Issue by Sinsgiri** [Sticktron/g0blin#231]
I can't stop the crashing but what I do is delete pandahelper the thing that allowed me to install g0blin then I download it reinstall g0blin and this is the important part on your homepage put the g0blin application on the left side of the cydia and that's how I fixed mine
Also I turned off low power mode charged it turn brightness up and sound up and I also deleted all notification and apps up I hope this helps

**Comment by Samgisaninja** [comment]
1. This is not an issue with the code of g0blin

2. Pandahelper is piracy
