### ISSUE TITLE
At the very beginning of install

### ISSUE THREAD

**Issue by JUSTplainSARGE** [Sticktron/g0blin#236]
I'm running 10.3.3 on first generation iPad Pro 12.9. Through ALL the latest jailbreak releases for 10.3.3 NEVER ONCE did Cydia Impactor complete the install. I ALWAYS GOT THE SAME ERROR. I tried on a different computer, thinking it must be the computer but STILL ended up with the SAME ERROR through ALL jailbreaks! I then thought it had to be Cydia Impactor! That is until I tried it on my smaller Air 2. Cydia Impactor completed the install without an issue! So, the ERROR all along has been my iPad Pro! And I have never gotten a stable working Cydia out of it! It crashes EVERY TIME I try to open it. Now, I just tried to install G0blin-RC2 and it crashes immediately with the ERROR ipa.ccp.444! Any help would be most appreciated! Thanks,
JUSTplainSARGE

**Comment by Sticktron** [comment]
This is an issue related to Cydia Impactor not g0blin. Closing.
