### ISSUE TITLE
G0blin nog opening after battery death/hard reboot

### ISSUE THREAD

**Issue by Polonskyi** [Sticktron/g0blin#237]
I sideloaded g0blin YESTERDAY, and everything was fine.
But every time my phone reboots or dies, g0blin won't open, none of my sideloaded apps open...
I don't have daily access to a computer. 
Why does this happen ?

**Comment by Sticktron** [comment]
This jailbreak is semi-tethered, so you have to re-jailbreak whenever your phone turns off.
