### ISSUE TITLE
Impactor error

### ISSUE THREAD

**Issue by jes-13** [Sticktron/g0blin#238]
Using RC2:
Cydia Impactor reports and error during install. 
Goblin installs, Cydia is installed.
![screen shot 2018-02-07 at 6 30 58 pm](https://user-images.githubusercontent.com/36251344/35952529-42aaaefc-0c35-11e8-8f30-d5b0c80672f4.png)

**Comment by Sticktron** [comment]
You can ignore that "error"... it's just some quirk of Impactor. It doesn't affect the app you install.
