### ISSUE TITLE
FIX BLANK SCREEN CYDIA

### ISSUE THREAD

**Issue by WitchSn0w** [Sticktron/g0blin#24]
After many experiments I managed to start Cydia avoiding the white screen.
Simply open cydia wait a couple of seconds back home and open g0blin, wait a few seconds and reopen cydia. (Repeat the operation until it starts)
With this trick I managed to start cydia, this does not mean that it works for everyone.
Expect a more stable version of g0blin and thank the developer.

*Cydia does not install Tweak, you can add repositories but when you install a tweak simply download the package without installing it on your device.

**Comment by zawata** [comment]
Yeah I don't think it's that complicated.

My cydia opened to a blank screen and I just let it sit for like 5-10 seconds before it started right up.

**Comment by WitchSn0w** [comment]
A large share of users find themselves cydia that after a few seconds crashes.

**Comment by pedroadelino** [comment]
I have a fix for white screen, I will add it to my GitHub repo soon. Stay tuned.
