### ISSUE TITLE
cydo was down under preRC3

### ISSUE THREAD

**Issue by xhj14012** [Sticktron/g0blin#252]
cydia return error code(2), and mterminal return Exit 1. It didn't be fix by delete cydia and reinstall:(6s,10.3.3)

**Comment by andrewathalye** [comment]
6s 10.3.3 is not supported I think. Sticktron is waiting for some help to add it last I checked.

**Comment by xhj14012** [comment]
Already fixed in latest build:P

**Comment by OmegaXIV** [comment]
try Audicy for import For download try safari plus
