### ISSUE TITLE
Reboots after jailbreaking

### ISSUE THREAD

**Issue by JohnnyZer0** [Sticktron/g0blin#26]
title

**Comment by zawata** [comment]
It may do that a few times. You should try again. Also reinstall bootstrap.

Mine rebooted on the first try but got it on the second.

**Comment by pridhvi10** [comment]
I jailbroke successfully on the first try. installed a tweak and after installation it asked for 'reboot' instead of respring. I went ahead and rebooted the device. Now the G0blin app wont jailbreak. Either it restarts or says failed, try again. Please help!

**Comment by Sticktron** [comment]
not applicable to RC0
