### ISSUE TITLE
Deleted g0blin , cydia impactor not working.

### ISSUE THREAD

**Issue by HoldThemStill** [Sticktron/g0blin#267]
I have deleted g0blin by accident I got mad when my phone rebooted and couldn't click on either g0blin or cydia the smart thing to do would be put it in safe mode but I was mad so deleted g0blin, so I was just going to rejailbreak no big deal, but when I open cydia impactor I run into the biggest problem I've ever seen it started by me not even being able to click on revoke cert than turned into a number of different error codes that no one seems to know what they mean I mean I searched far and wide with no answers I even tried downloaded older versions of cydia impactor with no help i now have it on error 81 an easy fix but for whatever reason won't let me get a new certificate. Someone please help.

**Comment by andrewathalye** [comment]
Wait a day or so, rediwnload impactor, try revoking and deleting app id, try maybe with a new Apple ID , and, at last, try reinstalling windows / rebooting your router. Don't reset your phone as that could brick it pretty nicely.

**Comment by HoldThemStill** [comment]
I have reset my phone and is fine I still have cydia and all just can't get impactor to work

**Comment by andrewathalye** [comment]
Could you post a screenshot / video?
That would help a lot.
Also, although I IMMENSELY respect saurik, its kind of mean for him to not make Impactor open source.

**Comment by HoldThemStill** [comment]
![image](https://user-images.githubusercontent.com/36541777/36361138-a079e816-14f7-11e8-9907-305b1d01a566.jpg)

**Comment by andrewathalye** [comment]
Thanks. You are trying to revoke certificates? Download Cydia Impactor 0.9.43, try that again, and then use the latest version to install g0blin.

**Comment by andrewathalye** [comment]
![image](https://user-images.githubusercontent.com/30047830/36361326-f40d93bc-1522-11e8-8b20-03114303f263.png)
That error is caused by using the latest version of C.I. to revoke a cert or app id.
0.9.43 was the latest version (for some reason) that could succeed in doing that.

**Comment by HoldThemStill** [comment]
Yes revoking cert and i downloaded 0.941 to try it and t didn't work

**Comment by andrewathalye** [comment]
0.9.43 can though
I'd provide a zip but that seems to be frowned upon on Github.

**Comment by HoldThemStill** [comment]
Could you email it to me?

**Comment by andrewathalye** [comment]
[0.9.43_Impactor.zip](https://github.com/Sticktron/g0blin/files/1735481/0.9.43_Impactor.zip)
SHA-1 c8d1137e1fc38e5db7b3daa87aa3136283a18285

**Comment by andrewathalye** [comment]
Try that to revoke the certs. Then delete the profile from your phone (if its even on there), and try to install the ipa with the latest impactor

**Comment by HoldThemStill** [comment]
I was able to revoke cert witch thank you by the way that's the farthest I've gotten but while trying to get rid of delete app I'd

**Comment by HoldThemStill** [comment]
![image](https://user-images.githubusercontent.com/36541777/36361596-610f1fbc-14fb-11e8-89e0-c106ec755bd2.jpg)
I get this

**Comment by HoldThemStill** [comment]
When trying to put g0blin into cydia impactor it does the same thing

**Comment by andrewathalye** [comment]
Now use Impactor 0.9.44 to install the g0blin ipa. This is the latest version. The older versions don't work (APple blocked 'em)

**Comment by HoldThemStill** [comment]
Damn dude you helped me out I owe you a big one thank you so much really

**Comment by HoldThemStill** [comment]
I am going to have to have you help me again but I have g0blin on there now every time I try to jail break it fails but still thank you man can't thank you enough

**Comment by andrewathalye** [comment]
Put your phone into aeroplane mode, let it sit for a bit, open the g0blin app, wait for cpu usage to be less than 5%, and try again .

**Comment by miguelsaliba** [comment]
I'm having similar issues, whether the CPU is less than 5% or not. I don't know what to do.

**Comment by andrewathalye** [comment]
Is your phone in aeroplane mode? What is your phone's model? What iOS are you on?

**Comment by andrewathalye** [comment]
Any other issues? Otherwise pls close the issue, thx.

**Comment by HoldThemStill** [comment]
I think I got it all sorted around thank you man if I'll deff recommend you to someone if they need help thank you again, I'll be in touch. Thank you (again)
