### ISSUE TITLE
Device not supported ip6s- iOS10.3.3

### ISSUE THREAD

**Issue by mullapudirohith** [Sticktron/g0blin#27]
When I compiled and opened the app, it surprisingly says that the device isn't supported.Is it wrong with my board confit? or something els. I'm running iOS 10.3.3(14G60? on iPhone 6s

**Comment by zawata** [comment]
This hasn't been complied and released because it's not done yet.

You will need to find and integrate the offsets for your device to use it. I've got a 6s on 10.3.3.
