### ISSUE TITLE
Device Not supported

### ISSUE THREAD

**Issue by IItzRyan** [Sticktron/g0blin#289]
Im on ios 11.3 latest beta and i have a iphone 6 and will not let me jailbrake.ait says Device not supported. Does it not work on iphone 6’s?

**Comment by x0009** [comment]
It's cuz ur on the latest version

**Comment by x0009** [comment]
Only supports 10.3-10.3.3

**Comment by IItzRyan** [comment]
Any way to downgrade even when its not sighned by apple? I really want to jailbrake.

**Comment by nik312123** [comment]
You cannot. The best method is to simply wait and not upgrade your iOS. You could downgrade to 11.2.6 if you wish, though. That would slightly increase your chances of getting a jailbreak earlier.

You should close this issue since it does not pertain to g0blin.
