### ISSUE TITLE
How do we give entitlement to 3rd party root apps?

### ISSUE THREAD

**Issue by arinc9** [Sticktron/g0blin#29]
Just letting you know it is working quite well on my i6+ 10.3.1. No random reboots because of KPP bypass, substrate working. And can you provide more information about giving root priviledge entitlement to 3rd party root apps?

**Comment by mohammedtabish** [comment]
Check the readme.md

**Comment by arinc9** [comment]
Oh wow good job! Have never seen that before now I exactly know what I have to do!

Stop underestimating people.

**Comment by mohammedtabish** [comment]
You own a macbook?

**Comment by zawata** [comment]
The readme contains the key to add but essentially:

In the root of an app's folder there's a file I believe is called entitlements.plist. You just have to add the key into it(without breaking the file) 

You can accomplish that by either unzipping the IPA and modifying it then impacting it or by doing it via ssh.

I haven't actually done it as I haven't needed to yet, so this is mostly theoretical. I'll investigate further when it isn't 3am and post any changes(unless someone beats me to it)

**Comment by arinc9** [comment]
Well, it will stay on theory forever. Went to Filza's directory didn't see any file like that name. Copied one from another app Calculator, copied to /var/mobile/Documents to add the key, pasted to Filza's directory using cp command in ssh. Rebooted jailbroke again, nothing changed.

**Comment by arinc9** [comment]
@mohammedtabish No but I have macOS anyway.

**Comment by zawata** [comment]
so I did a little investigating and it turns out that i was mistaken.

Ran `grep -rnw '.' -e 'com.apple.private.security.no-container'` on the bootstrap and found `Binary file ./Applications/Cydia.app/Cydia matches`.
Meaning that the key is actually compiled into the binary in an app file. which sure enough its on line 3408 and 9400. 

This likely means the app has to be recompiled to allow for this. It may be possible to just add the key to a precompiled binary inside previous apps. I would give it a shot but my phone is currently rebooting when its supposed to be respringing so I can't investigate.

**Comment by arinc9** [comment]
Is there anything I can do here? My phone always works on the mostly first try. And I have macOS you can remotely control my PC.

**Comment by arinc9** [comment]
We can chat on Discord.

**Comment by arinc9** [comment]
@zawata just notifying you if github doesn't do automatically.

**Comment by mohammedtabish** [comment]
@arinc9 check out the xPreeks github , filza is working fine after using that jailbreak

**Comment by arinc9** [comment]
@mohammedtabish do you really think these kind of useless forks gonna fix that problem? I understand you're trying to learn but you're not in my level. If you check what @zawata said you can see we need to add entitlements into the executable of the root app. How that guy's fork gonna work on this you think? Oh but if you think "Filza is working" means you can launch the app without crash, that would prove that you know not much about what we're talking here.

**Comment by mohammedtabish** [comment]
Yeah i know "i am not on your level" i am just trying to help here , some one missed his alarm today

**Comment by arinc9** [comment]
I just hate people thinking how easy is doing all of these. It's not. Lots of devs spending their times, debugging, fixing these kind of issues but what you said? Just try someone else's useless work that the only changes he made was modifying the GUI to look like he made something big in the code. Stop giving attention to these kind of copy pasters. Go with guys like @zawata. He is trying to find a solution for this issue but you're only saying is "try something else that doesn't work but I'm telling it's working".

**Comment by zawata** [comment]
anyways... I'm on the jailbreak discord under zawata. ping me there

**Comment by arinc9** [comment]
@zawata are you the Zawa#4393?

**Comment by zawata** [comment]
I'm gonna say probably.

**Comment by arinc9** [comment]
K I'm arinc9#2874 btw.

**Comment by yur1xpp** [comment]
@arinc9 do you figured it out?

**Comment by arinc9** [comment]
Nope, still trying to finding a way to contact with @zawata.

**Comment by yur1xpp** [comment]
Alright, would you mind post an update here once you figured it out? Appreciate that! :)

**Comment by arinc9** [comment]
Will do.

**Comment by Dennisbonke** [comment]
allright, tried it with jtool and ldid, and MTerminal still refuses to work. Does it require a reboot or so?

**Comment by arinc9** [comment]
What did you actually do with jtool and ldid?

**Comment by Dennisbonke** [comment]
give entitlements to MTerminal, after reboot and rejailbreak MTerminal works!
just use ldid, that works best.

[ent.txt](https://github.com/Sticktron/g0blin/files/1604017/ent.txt)

save that on your phone as /var/root/ent.xml, ssh to /Applications/MTerminal.app/ and run ldid -S/var/root/ent.xml, reboot and rejailbreak, and profit

**Comment by arinc9** [comment]
That didn't work. Literally did everything you said correctly. Let me explain what I did:

cd to mterminal, ldid -S/var/root/Entitlements.xml, reboot.

**Comment by Dennisbonke** [comment]
ahem, the command is wrong, ldid -S/var/root/ent.xml MTerminal (the executable name is required after it) check with ldid -e MTerminal for <key>com.apple.private.security.no-container</key><true/>

**Comment by arinc9** [comment]
Now filza does not even launch. Probably made something wrong. Will check it.

**Comment by arinc9** [comment]
You're the best man! Its working now!

**Comment by Dennisbonke** [comment]
Filza has its own entitlements that need to be in the file aswell, else it will lose those. always check with ldid -e executable and copy the original entitlements to a file, add the com.apple.private.security.no-container one and ldid -S/path/to/entitlements.xml executable them, you can make a backup of the original executable in case you fucked up (i did that at first as well). As long as cydia works and you dont mess with stock app's (setup.app and such), you could always reinstall the app you were modifying to try again

**Comment by arinc9** [comment]
Yeah you're right. Will reinstall Filza nad MTerminal to check if it has other entitlements.

**Comment by arinc9** [comment]
Whoa, this mothafucka has lotta entitlements

**Comment by arinc9** [comment]
Mate thanks so much for that tutorial. Now I got all the correct entitlements for every app that I've installed from Cydia. Love ya!

**Comment by Dennisbonke** [comment]
No problem, glad I could help. Did you get crash reporter, anemone and / or Flex 3 working? They crash on startup for me (anemone sends me to safe mode and crashes there). Without crash reporter, I can't see what is messing with those apps

**Comment by arinc9** [comment]
Didn't try anemone and flex 3 but can confirm CrashReporter and GameGem doesn't work even after adding the entitlements.

**Comment by arinc9** [comment]
And can confirm Ext3nder works after that.

**Comment by Dennisbonke** [comment]
Ext3nder works here as well. Can you try flex 3 for me?

**Comment by arinc9** [comment]
OK. Just a sec.

**Comment by arinc9** [comment]
Yeah Flex 3 crashes after launch.

**Comment by Dennisbonke** [comment]
Hmmm. Maybe @Sticktron knows what is up? I gave it the sandbox entitlement

**Comment by arinc9** [comment]
I don't know. Anyway I need to sleep. See you soon!

**Comment by marlonalkan** [comment]
As I can't access my iPhone over SSH is there currently another way to add the entitlement to an app?
MTerminal can't be used because of the missing entitlement.

**Comment by Dennisbonke** [comment]
Not that I know of. It is really strange that ssh is not working for some (most) of us but that it worked out of the box for me

**Comment by arinc9** [comment]
Maybe it's because of the forgotten SSH in the bootstrap that added yesterday?

**Comment by iM4CH3T3** [comment]
Someone know why Idid -S not work for me ?
Idid command not found...

**Comment by arinc9** [comment]
Maybe you're trying it on mac instead of iOS.

**Comment by Hakim-Bou** [comment]
I don't have ssh access too, even after re-installing bootstrap with the last commit. (on i6s 10.3.3)

**Comment by arinc9** [comment]
Did you set the port as 2222?

**Comment by Hakim-Bou** [comment]
@arinc9 yes
```
ssh root@myiphere -p 2222
```

**Comment by arinc9** [comment]
You can try to connect to localhost in your device with an SSH client on App Store.

**Comment by Hakim-Bou** [comment]
@arinc9 Tried too, I got the error msg "Connection refused"

**Comment by iM4CH3T3** [comment]
Ssh into my iPhone from pc via windows cmd

**Comment by arinc9** [comment]
Both of you might wanna try Meridian jailbreak. Maybe you can get ssh correctly.

**Comment by Dennisbonke** [comment]
Yeah well, no kpp bypass there so no substrate and ldid is part of Link Identity Editor - pseudo-codesign Mach-O files

http://cydia.saurik.com/package/ldid/

Install that for ldid

**Comment by arinc9** [comment]
I mean my friend was having ssh issues as well but he fixed it with using Meridian's bootstrap then he rejailbreak with g0blin.

**Comment by Dennisbonke** [comment]
That may work

**Comment by lowzyyy** [comment]
i did meridian jailbreak after g0blin and nothing, same error, connection timeout

**Comment by yur1xpp** [comment]
Hey @arinc9, you said Ext3nder works for you, does it resign app? Mine stuck at loading (after gave the entitlement)

**Comment by arinc9** [comment]
I'm using Ext3nder Installer, not Cydia Extender.

**Comment by frankthedead** [comment]
I'm getting this error: ldid.cpp(443): _assert(false); errno=0
Any ideas what could it be?

**Comment by Dennisbonke** [comment]
I would need the command that you used to help you

**Comment by yur1xpp** [comment]
@arinc9 Yeah it's Ext3nder Installer. Have you try to resign the app? If yours is working I wonder was is wrong with mine. I'm getting the error: 

./plist.hpp:394 _assert(plist != NULL)

You happen to know why?

**Comment by robonxt** [comment]
Well I'm getting: 

./minimal/mapping.h(54): _assert(false); errno=2

When I try to entitle Ext3nder...

**Comment by Dennisbonke** [comment]
Command that you used plz? Else i can't help you

**Comment by robonxt** [comment]
cd /Applications/Ext3nder.app/ && ldid -S/var/mobile/Documents/ent.xml Ext3nder

It works with filza, WhiteTerminal, and MTerminal, but CrackTool2 and Ext3nder both gave the same error.

**Comment by 61Halim** [comment]
i find your problem, on Ext3nder.app is the .exe Extender
try this cd /Applications/Ext3nder.app/ && ldid -S/var/mobile/Documents/ent.xml Extender

**Comment by robonxt** [comment]
@61Halim It works! Thanks a bunch! Now time to search for more tweaks to install ;)

**Comment by schu7max** [comment]
Hi every1 - i have no knowledge wso about this - i only have iphone6 and win pc - what do i need to make mterminal work (there is some weard screen with lines and big box when i start it) - or maybe i dont need mterminal - only one deb file i need to install and dont know how - ifile cant or filza install it (filza says there is some problem with terminal) and ifile cant even start (few days ago it could but still couldnt istall that deb).. if someone is willing to help please - and to others - have a nice day :)

**Comment by arinc9** [comment]
I can show you step by step with teamviewer and discord.

**Comment by schu7max** [comment]
you would do that?

**Comment by arinc9** [comment]
Yeah why not?

**Comment by schu7max** [comment]
whell - i expected little help, nit that much :)

**Comment by schu7max** [comment]
ok - when u have time (and if you still have will) we (you :)) can try it

**Comment by arinc9** [comment]
I'm ready right now add me on discord. arinc9#2874

**Comment by schu7max** [comment]
i think i added you - have never used it befor so i think i made it..

**Comment by arinc9** [comment]
ok go message me from there, i cant message you strangely.

**Comment by Naimat7c** [comment]
PLease can you help friend @arinc9  i have teamviewer and iphone 6 i dont know how to give acces root to 3rd party apps im on 10.3.3 G0blin

**Comment by arinc9** [comment]
You don't need it anymore dude.

**Comment by HLixir** [comment]
is gamegem fixed for this yet?

**Comment by arinc9** [comment]
Just use my tutorial to get some of the crash on launch apps work. It's for Cydia Eraser but the Tutorial section should work for GameGem.

https://reddit.com/r/jailbreak/comments/809ahv/tutorial_how_to_make_cydia_eraser_work_on_ios_103x/

**Comment by HLixir** [comment]
THAK YOU SO MUCH! i had to type it _MemSearch because the first one wasn't the other way around
