### ISSUE TITLE
Tweaks fail to install

### ISSUE THREAD

**Issue by jjore123** [Sticktron/g0blin#30]
When installing tweaks, I'm left with Done: "tweak"

**Comment by mohammedtabish** [comment]
Check the readme

**Comment by zawata** [comment]
The readme doesn't say anything related to this.

Check that you've compiled the latest version and try again.

**Comment by jjroe123** [comment]
Compiled again, no progress.

**Comment by jjore123** [comment]
^wrong account

**Comment by Drozd228** [comment]
1. Add http://cydia.ichitaso.com repo in cydia
2. Download&install Dropbear
3. Respring Your iPhone 
4. Download PuTTY
5. Connect iPhone to PuTTY root@youripadress port 2222
6. PROFIT, Enter your commands in SSH
