### ISSUE TITLE
iPhone 5S 10.3.3 GPS seems broken under g0blin

### ISSUE THREAD

**Issue by HuFVdk** [Sticktron/g0blin#32]
When I use jailbroken mode,GPS doesn't work anymore,using latest version

**Comment by Jakob-Rangel** [comment]
GPS is also not working for me either.  Didn't realize till just now.

**Comment by tutihun192** [comment]
iPhone SE 10.3.3 - **GPS also not working**

**Comment by zawata** [comment]
Reported on 6s. Likely not a device specific problem. 

I've heard that people used to experience similar problems in Yalu and this it was/may have been resolved. I may look into how that was done.

Google maps/waze is an alternative.

**Comment by ammartaip** [comment]
iP6s 10.3.1, GPS not working too. Not even in Google Maps.

**Comment by tutihun192** [comment]
If you set location to _"always on"_ for maps, gps will work. If you have (like I did) _"only when using"_ for some reason it doesn't activate and the little arrow indicator doesn't show

**Comment by ammartaip** [comment]
@tutihun192 still, it didn't work for me.Basically GPS signal is not available in every application in my device. How did u make it work for your maps application ?

**Comment by robonxt** [comment]
iPhone 5s, iOS 10.3.3 same problem. Maybe it has something to do with that no-icon Springboard setting in locations that wasn't there before?

**Comment by RootSir** [comment]
6s 10.3.2 same issue.

**Comment by lovelife17** [comment]
Gps was working for me only in waze and google maps in Ios 10.3.3 6s plus. Tomtom navigon was not working. When i reset network setting and jailbreak again google maps and waze stops working. Maybe is a a trick or something. Any ideas?

**Comment by minipicc95** [comment]
I have this problem too on my iPhone 6s and it works after I turn it back on when the jailbreak is disabled.

**Comment by ammartaip** [comment]
#71

**Comment by pr0be1** [comment]
Set location to "always on" for maps!
Download tweak "CCQuick Pro" and save "Location" as toggle.
So you can start/end gps fast if you need.

**Comment by Sticktron** [comment]
fixed as of RC0
