### ISSUE TITLE
How to install the JB tool?

### ISSUE THREAD

**Issue by b28963085** [Sticktron/g0blin#36]
I want to know how to install the JB tool? 
Because I can not find the ipa file from this tool ,
I hope someone will told me , thank you!

**Comment by deadmaus3221** [comment]
If you can't build the ipa by yourself, don't use this jailbreak yet.

**Comment by zawata** [comment]
Adding to what deadmaus said: it's not released yet because it's in development. You'd have to build it yourself and accept the risks of using it.

**Comment by MODZ4FUN420** [comment]
how would you build it zawata? And is it possible on windows 7?

**Comment by zawata** [comment]
I have a hackintosh. It is not.

**Comment by Drozd228** [comment]
github.com/xPreeks he is create ipa special for us

**Comment by Sticktron** [comment]
wait for an official release
