### ISSUE TITLE
Cydia Overlap

### ISSUE THREAD

**Issue by VinLark** [Sticktron/g0blin#37]
I have already used V0rtex, and that installed Cydia on my device. If I install this on my device, will is overlap? Will it bootloop my device? What would happen, if anything? Thanks

**Comment by zawata** [comment]
Nothing will happen.

**Comment by Sticktron** [comment]
v0rtex installs it's bootstrap files to /v0rtex, so it won't interfere with anything else. You can delete that folder after using g0blin.
