### ISSUE TITLE
After jailbreaking for some times, Cydia won't work | SSH won't work

### ISSUE THREAD

**Issue by deadmaus3221** [Sticktron/g0blin#38]
Just noticed this issue. iPhone 6s, 10.3.3. After the first jailbreaks, some people are getting a error that cydia doesn't show the installed packages (Cydia Installer, Translations and Patcyh show up in red) and no packages install due to cydia can't exec dpkg! My guess is that re-installing boostrap is messing with previous instalations and will break cydia.

Also, for some people ssh never works, for me personally it worked on the first jailbreak execution, but breaks on further jailbreak attempts.

EDIT on further investigation:
 - dpkg permissions are fine (0755)
 - Filza works perfectly after JB, the only issue is with Cydia.
 - Suddently, cydia won't open, just splashes a cydia image low res over the screen and closes
 - After many re-installs of the bootstrap, cydia keeps failing to open and still no ssh
 - Cydia open as normal again, but has this screen on packages: https://i.imgur.com/GOELFUB.jpg
 - When installing a package (for example, cydia substrate): https://i.imgur.com/lT8Y6DB.jpg
 - As noticed, cydia substrate installation removes cydia, so it needs a reinstall of the bootstrap: https://i.imgur.com/L8Pb19t.jpg
  
  SUPER MEGA ULTRA EDIT:

 - I fixed the issue by deleting all content and definitions on my phone, and after setting up and activating it, run g0blin with force re-install bootstrap. All good now. Still strange the issue. I don't know if I should close it as ssh still doesn't work...

**Comment by Drozd228** [comment]
1. Add http://cydia.ichitaso.com repo in cydia
2. Download&install Dropbear
3. Respring Your iPhone 
4. Download PuTTY
5. Connect iPhone to PuTTY root@youripadress port 2222

**Comment by mrd-mrd** [comment]
@Drozd228 I used this , but SSH is still not working
