### ISSUE TITLE
Spawning SSH Server

### ISSUE THREAD

**Issue by Jakob-Rangel** [Sticktron/g0blin#39]
Maybe I'm missing something, but I believe the README says that it spawns an SSH server on the port 2222.  However, it appears that this is not functioning as it should since Putty is not working and giving me a connection refused error on that port.

Edit: Aside from the SSH, the project is flawless.  Tweaks work etc, however the root entitlements fix for applications is something I look forward to being fixed, as well as a fix for the GPS not working.
More Info:
Device: iPhone 6 [GSM]
iOS: 10.3.2

**Comment by callum-99** [comment]
Problem is /usr/local/bin/dropbear doesn't exist. To fix just copy /usr/local from yalu102's bootstrap to g0blins bootstrap.

**Comment by WitchSn0w** [comment]
Please tell me how to install tweaks and ssh server.
Sorry but I'm not informed with this..

**Comment by zawata** [comment]
This issue should be fixed with the latest commit.

**Comment by Jakob-Rangel** [comment]
Yeah it's resolved now.
