### ISSUE TITLE
Cydia...

### ISSUE THREAD

**Issue by Aceoro** [Sticktron/g0blin#4]
So I can't believe you got this to work, thank you. It took about 7 tries to jailbreak. 

However there seems to be issues with Cydia (as expected).

Firstly, I had to create the folder '/etc/apt/preferences.d' and '/etc/apt/apt.conf.d/' in order for APT to work correctly.
APT works fine within Cydia (after the 2 fixes).

However, dpkg does not... 

Cydia will throw out:

> dpkg: requested operation requires superuser privilege
>Sub-process /usr/libexec/cydia/cydo returned an error code (2)

Thanks.

**Comment by Danoded** [comment]
Try this:

SSH into your device/open mobile terminal and run apt-get update as super user.

**Comment by Sticktron** [comment]
cydo doesn't work yet, due to an underlying problem with the jailbreak. I'm working on it.
