### ISSUE TITLE
Compile on windows 7 help

### ISSUE THREAD

**Issue by MODZ4FUN420** [Sticktron/g0blin#40]
is there any way to compile this with out a mac or a virtual mac? If so any links how?

**Comment by zawata** [comment]
nope.

**Comment by swing7wing** [comment]
This shouldn't be an issue, if you don't know how to compile this project, you shouldn't use it. It is still in development. 
Please close this issue.

**Comment by MODZ4FUN420** [comment]
Not if your trying to learn.

**Comment by robonxt** [comment]
Compiling ios apps only works on Macs. I had to borrow a macbook just to install it on my iphone.

**Comment by TechdudeGames** [comment]
If you don't have a mac or the ability to get a mac, you might want to look into setting up Hackintosh on your system.

**Comment by Sticktron** [comment]
Like the others said: VM, Hackintosh, or Mac. Beyond that I can't help you, I have no experience writing Mac software while using Windows.
