### ISSUE TITLE
Apps that locked using TouchID won't prompt for TouchID input

### ISSUE THREAD

**Issue by yur1xpp** [Sticktron/g0blin#46]
Apps like Apollo wont prompt for TouchID and will keep stuck at the Lock logo. Another app, KeePass Touch, too. If the key database is clicked, a message box "User interaction is required" will pop up. All those apps work fine in unjailbroken state.

Thanks for the JB Sticktron :)

EDIT: iPhone 6, 10.3.3

**Comment by leepattison** [comment]
iPhone 6 iOS 10.3.1 Same problem on banking apps and making purchases AppStore/ApplePay the Touch ID input alert doesn't show.

**Comment by dallwine3** [comment]
iPhone 6s 10.3.3        I'm having the same issue. I use TouchID to unlock my OnePassword and email accounts and it won't work post-jailbreak.

**Comment by arx8x** [comment]
I've tracked the issue down to daemons. Please don't make duplicate issues

**Comment by Sticktron** [comment]
moved to #84
