### ISSUE TITLE
iPhone 6s 10.3.3

### ISSUE THREAD

**Issue by JohnnyZer0** [Sticktron/g0blin#5]
Ok, so I just can't wait anymore and I decided to give it a try. It says device not supported on iPhone 6s. I compiled with Xcode 9.2 and that is all.

**Comment by Aceoro** [comment]
You need to supply your own offsets.

**Comment by JohnnyZer0** [comment]
Oh-oh. This is will be a problem for me because I have no idea to do anything besides design in Xcode haha. Guess I'll wait.
