### ISSUE TITLE
SSH Still Not Working?

### ISSUE THREAD

**Issue by Jakob-Rangel** [Sticktron/g0blin#54]
Made an issue about this yesterday but closed it after I learned it may have been fixed with this next update, however despite force reinstalling bootstrap and making sure everything worked nicely, Dropbear/SSH connectivity is not working.  When trying to connect to my devices IP through Putty using port 2222, I get:
https://gyazo.com/a3732b569b8fbb8cdd3caa9554447ed8
And it instantly drops the connection.  I tried installing and uninstalling OpenSSH both led to the same result.

Anyone else having this issue?

**Comment by kngslav** [comment]
i get Network error connection refused, hoping it will get fixed soon

**Comment by Dennisbonke** [comment]
Worked out of the box here

**Comment by kotjiac** [comment]
SSH not working for me. nmap does not show port 2222 listen in iPhone IP.

**Comment by kngslav** [comment]
I fixed it!! Reboot then sideload meridian then Jailbreak using it, when its done Jailbreak using g0blin, now port 2222 will be open!! Dont forget to change your password

**Comment by itsmidnightyo** [comment]
i can confirm with @kngslav that this works. it is quite frustrating to complete at first since it fails and reboots a bunch of time, but it eventually connects via KiTTY. :))

proof:

![](https://i.imgur.com/1ONJx2T.png)

**Comment by kotjiac** [comment]
I tried jailbreak using g0blin, after jailbreak using meridian, but iPhone reboots all the time.

If I try very very times, in sometime would I have success?

**Comment by kotjiac** [comment]
Important: what version of meridian?

pb1? pb2? pb3?

**Comment by kngslav** [comment]
threre is antother fix aswell https://www.reddit.com/r/jailbreak/comments/7oj564/tutorial_how_to_access_ssh_using_dropbear_in_ios/

**Comment by kotjiac** [comment]
If reboots, is necessary jailbreak with meridian and then use g0blin?

**Comment by kngslav** [comment]
if you check out the reddit link i sent its easier

**Comment by kotjiac** [comment]
Thank you very much. Using reddit link instructions I got SSH working and Filza with root privileges, too!

**Comment by kngslav** [comment]
Glad to help! 👍

**Comment by Jakob-Rangel** [comment]
Might as well close this, solved it a few days ago using:
https://www.reddit.com/r/jailbreak/comments/7oj564/tutorial_how_to_access_ssh_using_dropbear_in_ios/
Very simple to do.
