### ISSUE TITLE
Doesn’t support A7 iPad mini 4

### ISSUE THREAD

**Issue by totbun** [Sticktron/g0blin#55]
When I open g0blin I get a message saying that the device is not supported even tho i am 10.3.3 and have a 64 bit device.

**Comment by zawata** [comment]
If you would read #27 #3 #5 #9 #31 #52 or #45 (theres probably more I'm just too lazy to find them)

This is still in development. You need to find your device's offset and compile it yourself. This is documented in the original v0rtex repo as well as coutless other places.
