### ISSUE TITLE
Failed, Try Again.

### ISSUE THREAD

**Issue by pridhvi10** [Sticktron/g0blin#57]
I jailbroke successfully on the first try. installed a tweak and after installation it asked for 'reboot' instead of respring. I went ahead and rebooted the device. Now the G0blin app wont jailbreak. Either it restarts or says failed, try again. Please help!

**Comment by burhangee** [comment]
which tweak and what device? version? version of g0blin?

**Comment by iM4CH3T3** [comment]
Tap and hold volume up button and then rejailbreak... into noSubstrateMode. After that launch cydia and remove the faulty tweak...

**Comment by pridhvi10** [comment]
@burhangee Tweak was AudioRecorder 2 and device is iPhone 6s+ on iOS 10.3.3
G0blin version is the latest one.

**Comment by pridhvi10** [comment]
@iM4CH3T3 Would you please elaborate? I'm using g0blin jailbreak tool.

**Comment by iM4CH3T3** [comment]
Wait 80 seconds after reboot. Then tap and hold the volume up button and then tap jailbreak. Keep holding the volume up button till you see lockscreen.
