### ISSUE TITLE
g0blin doesn't support iPad 2017/9.7 inch?

### ISSUE THREAD

**Issue by byt3d3lux3** [Sticktron/g0blin#58]
My device has an A9 Processor and is on 10.3.1. I don't get it, I thought the jailbreak supports ALL 64bit DEVICES from A7 - A9 Processors. iPad6,11 a.k.a iPad 2017/9.7inch. And no it is not the iPad Pro 9.7inch

**Comment by arx8x** [comment]
It's a work in progress. Currently, g0blin only has support for a single device and OS. If you want to test, you have to add offsets for your device (from my fork?)

**Comment by WitchSn0w** [comment]
You must go in offset.m and change it
