### ISSUE TITLE
Where to add entitlement for iFile to work ?

### ISSUE THREAD

**Issue by lowzyyy** [Sticktron/g0blin#59]
Where we need to put that line, can u give us an example?

**Comment by Dennisbonke** [comment]
See issue 29 for Filza example. Filza is better than Ifile as ifile has some major bugs in it

**Comment by lowzyyy** [comment]
I cant find issue 29. It goes 28 then 30

**Comment by lowzyyy** [comment]
i cant ssh to my phone, when i try with putty or cyberduck its says timed out. IfunBox said that my phone is Jailed. I cant install apple file conduit2  because of cannot connect to the server:
subprocess new extra-installation script returned error exit status 1
sub-process  usr/libexec/cydia/cydo returned an error code 1

**Comment by Dennisbonke** [comment]
Oh you have the ssh problem as well? Join the others, and wait for sticktron

**Comment by robonxt** [comment]
#48 has an solution to the ssh problem and that's what I did to get into my iphone.

**Comment by mrd-mrd** [comment]
@robonxt I used this , but SSH is still not working

**Comment by KingMczjk** [comment]
I have this same issue I did the step to side load meridian etc still don't work

**Comment by mrd-mrd** [comment]
You can try this way @KingMczjk 
 https://www.reddit.com/r/jailbreak/comments/7oj564/tutorial_how_to_access_ssh_using_dropbear_in_ios/

**Comment by Sticktron** [comment]
not applicable as of RC0
