### ISSUE TITLE
iPhone 6 10.3.1 "Failed to remount system partition"

### ISSUE THREAD

**Issue by Darkaim63** [Sticktron/g0blin#6]
Title ^^

**Comment by MrARM** [comment]
**offsets.m**

Please close this.

**Comment by jakeajames** [comment]
@Sticktron sorry if I sound too stupid but, didn't Luca say the KPP bypass had to be updated? You're using the exact same code. Are you sure you aren't just lucky and the timeframe between two KPP checks was just too big?

**Comment by Dennisbonke** [comment]
That may well be, but being jail broken with g0blin for a while now I noticed no random reboots whatsoever. Only downside with g0blin is that I need to reinstall all the tweaks after reboot :(. So it seems that the kpp bypass works fine

**Comment by Sticktron** [comment]
@jakeajames I have no idea what I'm doing.
@Dennisbonke Latest build no longer reinstalls the bootstrap every time you jailbreak, which means your tweaks should still be correctly installed when you re-jailbreak.
