### ISSUE TITLE
ICleaner,Anemone and Bytafont 3 all crash on startup

### ISSUE THREAD

**Issue by herman21** [Sticktron/g0blin#60]
Hi, the jailbreak works fine and other tweaks aswell but Icleaner Anemone Bytafont 3 won't launch. they crash on startup. they just exit out.
Tweak list:
Anemone
Barrel
Boxy 3
Bytafont 3
Cydown
Eclipse 4
Groovylock
Icleaner
iwidgets
Lithium Ion
Lotus (theme)
Muze 2 (theme)
Power tap
SmoothPop
Sonus
Springtomize 4
Substrate Safe Mode
Swipe Back
WinterBoard

**Comment by Dennisbonke** [comment]
Power tap is broken, iCleaner use the beta repo, anemone is broken, bytafont 3 I don't know, may be entitlements (see issue 29). Also piracy (cydown) so no need to ask for help on Reddit or discord

**Comment by herman21** [comment]
I just want to test tweaks out before I buy them. I deleted Icleaner anemone and bytafont where do I find issue 29?

**Comment by Dennisbonke** [comment]
Under the closed issues

**Comment by zawata** [comment]
You can link to issues by just doing a number win follow by the issue number btw. 

#29

**Comment by herman21** [comment]
Ah now I understand, thanks!

**Comment by Sticktron** [comment]
Anemone needs an update; iCleaner works for me; RC0 fixes need for extra entitlement.
