### ISSUE TITLE
doesnt work ipad air 2 (ios 10.3.3-14g50) chip=A8X.  It only reboots?

### ISSUE THREAD

**Issue by minefreaky** [Sticktron/g0blin#61]
when i try to run the jailbreak it fails when i try again it just reboots and it does that again and again.

**Comment by Tyborg3** [comment]
Keep trying. I don't know if your device is supported or not but sometimes it takes to long to re-jailbreak. Try waiting a minute after you open the g0blin app and also try to jailbreak in airplane mode. Good luck!

**Comment by Sticktron** [comment]
not applicable to RC0
