### ISSUE TITLE
Crash midway of Jailbreak - reboot loop

### ISSUE THREAD

**Issue by PsychoticMan** [Sticktron/g0blin#62]
iPhone SE 16gb - Verizon 
iOS: 10.3.3

Used most updated Impactor & xPreeks G0blin.ipa file
Windows 7 computer

1st attempt:
Checked iPhone storage to make sure it wasn't getting full but had 3 gigs left.
After clicking the Jailbreak button, I see the jailbreak loading and the phone would restart (needing to type pass code after booting up). No cydia was found - g0blin app wont open up anymore. Checked Device Management and it was still verified.

2nd attempt: 
Deleted g0blin through Device Management in Settings>General.
Downloaded g0blin.ipa again and sideloaded
Verified the app
Opened the app successfully and I see the "ready" at the bottom screen.
Clicked jailbreak but the same thing happens as the first attempt.

3rd attempt:
Deleted g0blin from home screen
Downloaded g0blin.ipa again and sideloaded
Verified app
Opened the app and everything seems normal.
Clicked jailbreak and crashes instantly! Goes back to home screen and then reboots itself.

4th & 5th attempt:
Repeated 2nd & 3rd attempts but downloaded and sideloaded using my laptop instead
same problem

6th attempt:
Deleted g0blin through Device Management
Downloaded g0blin.ipa again and sideloaded using my desktop
Verified app
Opened the app and everything is again normal.
**Remembered that I had trouble with sideload NvwaStone jailbreaking with iPhone 5s iOS 9.3.3 when device was plugged into a computer or a cube** 
**also remember I had issues with opening camera when device was plugged in, computer or cube, after jailbreak; would force restart & needed to jailbreak again**
Unplugged iPhone SE
Clicked Jailbreak and everything worked!
Phone was not restarted (did not need type the passcode after. Used touch ID to unlock)
Cydia was on home screen and opened normally. 

I don't know if anyone else had this issue about the phone being plugged in.
I tried looking up if anyone else had this problem but didn't find a thread on it (since iphone 5S ios 9.3.2 and 9.3.3).
I would just like to bring my issue into the light. Hope anyone that is experiencing this issue can confirm this problem and solution.

PS: It is not my charging cable that is messed up. I bought a new Apple lightning cable thinking it was the problem but it was still giving me the same problem. Even tried different USB ports and even different computers. Even got a new phone thinking it was just the phone but same problem on the iPhone SE as the iPhone 5s.

**Comment by Dennisbonke** [comment]
xPreeks is Not This github repo. Report bugs for that fork there, not here
