### ISSUE TITLE
can u add support to the ipad air 1 ios 10.2.1 because i cant use it atm 

### ISSUE THREAD

**Issue by nimaxmodz** [Sticktron/g0blin#63]

**Comment by nimaxmodz** [comment]
or can someone give me the offsets for ipad air if that is going to fix my problem

**Comment by nimaxmodz** [comment]
why did u remove ipad air offsets?

**Comment by ecaslak** [comment]
I would use [Saigon-v0rtex by iabem97](https://github.com/iabem97/saigon-v0rtex) to jailbreak your device. It supports your device and firmware according to the readme, and it doesn't have any of the issues g0blin currently does (entitlement for GUI root apps, Touch ID, etc). It is possible that it doesn't have your offsets, as I didn't look through the source code.

**Comment by Sticktron** [comment]
g0blin is designed for iOS 10.3.x (A7 - A9 devices)
