### ISSUE TITLE
iPhone 6 10.3.1 panics afte a few hours then I have to rejailbreak 

### ISSUE THREAD

**Issue by Gabriel567ist** [Sticktron/g0blin#64]

**Comment by Tyborg3** [comment]
Wow, this jailbreak works pretty good for me. Maybe yours crash because of incompatible tweaks or maybe you have too much tweaks that your iphone 6 cant handle for too long?

**Comment by Dennisbonke** [comment]
No crashes here iPhone 6 iOS 10.3.1

**Comment by Sticktron** [comment]
if the issue persists after using the official release please open a new issue.
