### ISSUE TITLE
What tweaks are compitable? 

### ISSUE THREAD

**Issue by Gabriel567ist** [Sticktron/g0blin#65]
10.3.1 iPhone 6

**Comment by Dennisbonke** [comment]
Check the tweak list here: https://docs.google.com/spreadsheets/d/1r9jSb2-WuwnEC6nIxdJRdgaxhj6SrNJgER9JnVQwWn0/htmlview

**Comment by robonxt** [comment]
Or install tweakCompatible from Cydia, I reported some common tweaks as working for g0blin.
