### ISSUE TITLE
Cydia Installs. Not on Homescreen

### ISSUE THREAD

**Issue by chrisdarnel** [Sticktron/g0blin#68]
Cydia installs but doesn't appear on the homescreen. Can only be accessed via safari. All apps installed, Filza/icleaner/etc do not appear either outside of safari.

iPad 2017 6,11 10.3.2 

uicache and killall does not fix the issue. 
Force install bootstrap does not fix the issue

**Comment by Sticktron** [comment]
I don't know what you mean you say Apps can only be access via Safari.

Are you building g0blin from my source code?

**Comment by chrisdarnel** [comment]
Yes. I just added the offsets for iPad 5(2017).

Cydia and filza do not appear on the SpringBoard, but if I enter cydia:// or filza:// in safari, both will open.

Spotlight does not see them as installed apps either although they are present in /Applications

**Comment by chrisdarnel** [comment]
Issue RESOLVED.

"com.apple.springboard.plist" needs to have 'SBShowNonDefaultSystemApps' set to true(YES) for Cydia to appear on iPad 5.

Thanks to PsychoTea for the fix.

**Comment by Sticktron** [comment]
That is already set by g0blin.

**Comment by Sticktron** [comment]
I should double-check to make sure that plist edit is in fact taking place.

**Comment by chrisdarnel** [comment]
It was set to YES on my iphone 6, but it was set to NO on my iPad 5.

**Comment by nimaxmodz** [comment]
sticktron can you add the offsets for the ipad air?

**Comment by Sticktron** [comment]
if the issue persists in RC0 please open a new issue
