### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by lovelife17** [Sticktron/g0blin#70]
I use oral b app for my teeth and i use always bluetooth to connect oral b with my device. Is not connected with bluetooth anymore but when i reboot to remove jailbreak the counter in the oral b app counting. For example i had turned on the oral b app, tried to connect without success but without stoping oral b app and on the same time restarted app oral b showed me that was about the 2 minutes that supposed to show me if it was worked with jailreak.Also in the car i had to remove my device from memory and pair it again in order to work again! Any ideas? I already reset networks and i lost gps from google maps.

**Comment by Sticktron** [comment]
I have to remember to check this out, I'll update the issue when I do.

**Comment by zawata** [comment]
I don't that this is related. My car stereo worked just fine connected through Bluetooth when I was jailbroken.

**Comment by Sticktron** [comment]
noted, thanks.

**Comment by Sticktron** [comment]
@lovelife17 if the issue exists in an official release, open a new issue please.
