### ISSUE TITLE
Temp solution for Google Maps GPS problem

### ISSUE THREAD

**Issue by ammartaip** [Sticktron/g0blin#71]
Well, I know this issue was mentioned before. Someone even gave me solution that didn't work for me but after several tries it worked, not really well but still usable. I just wanted to put it separetlly with a more relevant title. 

1. Go to location service in privacy settings and turn it on.
2. set the GPS or Navigation application u want, for example Google Maps, on **always**.
3. reboot.
4. re-jailbreak
5. In case GPS is still not working, which was the case for me, download now **liblocation** from cydia.
hopefully GPS works now. 

--**Problems**:
* The GPS signal in going to work just in these applications, which are going to have the signal available ALL THE TIME IN THE BACKGROUND, **EVEN IF APPLICATION IS NOT BEING USED**. U can turn off the location service if you are not using the navigation, which is the only solution I know and then turn it on again when u need navigation. But whenever it's on, every application with ALWAYS will be working in the background, which is going to drain the battery.

* Not every application in the location service can be set to ALWAYS.

That worked for me on iPhone 6s with iOS 10.3.1.

**Comment by kotjiac** [comment]
Yes, it's works. Thanks for the temporary solution.

**Comment by vojkan069** [comment]
iphone 6 ios 10.3.3 not working

**Comment by vojkan069** [comment]
tweak caled liblocation ios 9.3.3 that not working

**Comment by Sticktron** [comment]
fixed in RC0
