### ISSUE TITLE
SSH Connection Refused iPhone 6 10.3.2

### ISSUE THREAD

**Issue by clavl23** [Sticktron/g0blin#73]
Hi there,

I have tried a lot to connect with ssh to can have access to my phone via wifi but when I try to connect my phone I get the connection was refused: https://image.prntscr.com/image/kGNUyVvZSI6OKQkyJhmwlA.png

**Comment by clavl23** [comment]
Rigt now I have solve the refused issue with Meridian but it still starting the session from a long time and not loading the phone : https://image.prntscr.com/image/dd7v3XtQSSm-Au0UZDIrSA.png

**Comment by lovelife17** [comment]
If you want with usb try this link
https://www.reddit.com/r/jailbreak/comments/7oj564/tutorial_how_to_access_ssh_using_dropbear_in_ios/

**Comment by clavl23** [comment]
@lovelife17 tahnk you very much! is working right now but I have one more question why i cannot install Apple File Conduit "2"? I get this sub process /usr/libexec/cydia/cydia returned an error code (1)!

Thank you one more time!

**Comment by deadmaus3221** [comment]
https://pastebin.com/u/deadmaus3221

**Comment by Sticktron** [comment]
fixed in RC0
