### ISSUE TITLE
Device get Hot and battery drain fast

### ISSUE THREAD

**Issue by kotjiac** [Sticktron/g0blin#74]
My iPhone get very hot and the battery drain very fast. I removed more and more cydia packages, but the problem persists. I can not discover how app, tweak or service is responsible.

**Comment by kotjiac** [comment]
I tried. I tried stop some daemons too.

**Comment by pr0be1** [comment]
You have to know, that's normal.
You phone will very hot so often you use cydia and install tweaks.
If you are ready (ready with your settings) and use your phone as far as before, then it will be normal temperature.
My phone will very hot, if camera app not closed in background.

(sorry for bad english)

**Comment by kotjiac** [comment]
I unistalled some packages: logrotate, php, ligthttpd, mysql and now all seems to be ok with temperature and battery.

(Sorry for my english, too)
