### ISSUE TITLE
No cydia installed on Ipad Pro 9.7

### ISSUE THREAD

**Issue by yanyuechuixue** [Sticktron/g0blin#88]
I have installed the ipa file. 
but no cydia is installed.

**Comment by Kristijan1001** [comment]
use cydia:// to access for now through Safari, same here iPad Air

**Comment by Sticktron** [comment]
There is a preference setting not being saved properly (my fault).

Manual Fix:

Add the following key to: _/User/Library/Preferences/com.apple.springboard.plist_
`SBShowNonDefaultSystemApps = YES`
