### ISSUE TITLE
Cannot add repos on iPhone 5s and Ipad Mini 2 ios 10.3.1

### ISSUE THREAD

**Issue by GrumpyOet** [Sticktron/g0blin#89]
(read title) I only see return to cydia and thats it.

**Comment by spockers** [comment]
Same.

**Comment by arinc9** [comment]
That's already known. No need to post here again.

**Comment by lcyenter** [comment]
It seems everyone has this problem,wait for updating

**Comment by Sticktron** [comment]
(cannot reproduce)

5S/10.3.1, 5S/10.3.3, Mini2/10.3.1 should all be working according to other testers.
