### ISSUE TITLE
Ipad air 2 wifi 10.3.3(14G5053A) beta 4 doenst work offsets arent supported

### ISSUE THREAD

**Issue by minefreaky** [Sticktron/g0blin#91]
Ipad air 2 wifi 10.3.3 beta 4 doenst work offsets arent supported
IM :(

**Comment by ecaslak** [comment]
Try changing the build number for iPad Air 2 on 10.3.3 under offsets.m (starting at line 657) to match your beta. It's possible the offsets are the same. 

If that doesn't work, change the offsets under your device and firmware except for Root Vnode (as it appears the same for all 10.3.x firmwares). You can find offsets using this guide: https://gist.github.com/uroboro/5b2b2b2aa1793132c4e91826ce844957. IPSW can be found here: https://www.theiphonewiki.com/wiki/Beta_Firmware/iPad/10.x#iPad_Air_2.

**Comment by Sticktron** [comment]
will be addressed in RC2
#117
