### ISSUE TITLE
iPad Air 10.3.2 , No Cydia on Springboard. Only way to access it is through Safari with cydia://

### ISSUE THREAD

**Issue by Kristijan1001** [Sticktron/g0blin#92]
iPad Air 10.3.2 , No Cydia on Springboard. Only way to access it is through Safari with cydia://

Jailbreak works , but no Cydia , a person told me that it doesn't have Reinstall Springboard in Cydia because it doesn't support it on my device ?

Workaround doesn't work because SBShowNonDefaultSystemApps is non existent in : /var/mobile/Library/Preferences/com.apple.springboard.plist

and adding the line manually after respring just removes it automatically

**Comment by af6** [comment]
try SSH + type in "su mobile" w/o quotes and enter/return then "uicache" and enter/return

(if that doesn't work then click the "i" before jb-ing and select "force-reinstall-bootstrap", until the jb works. :) )

**Comment by Kristijan1001** [comment]
Doesn't work, even tweaks icons dont show up like file zila manager

**Comment by af6** [comment]
weird... i cant even respring w/o a kernel panic. so, BE THANKFUL.

**Comment by Kristijan1001** [comment]
Thankfull for not being able to launch any tweak xD

**Comment by af6** [comment]
be thankful for the hard friggin work of these devs

**Comment by Kristijan1001** [comment]
i meant it in a way thankfull to my tablet that it worked at least abit, of course im thankfull to the dev lol

**Comment by JMccormick264** [comment]
There is a workaround listed https://github.com/Sticktron/g0blin/issues/68. Other's are having the same issue

**Comment by Kristijan1001** [comment]
JMccormick264 That doesn't work because SBShowNonDefaultSystemApps is non existent in : /var/mobile/Library/Preferences/com.apple.springboard.plist 

and adding the line manually after respring just removes it automatically

**Comment by Proxyworm** [comment]
can confirm, mine is blank also

ipad mini 4 10.3.2

**Comment by Sticktron** [comment]
done
