### ISSUE TITLE
cydia crashing on iPad Pro 9.7 on iOS 10.3.1

### ISSUE THREAD

**Issue by thecoolyguy585** [Sticktron/g0blin#96]
cydia shows up on my iPad pro but it always crashes. i used the new ipa RC1. is this because i have the A9X Chip rather than the A9 chip? please answer

**Comment by byt3d3lux3** [comment]
Are you in the springboard? Try and force reinstall bootstrap

**Comment by Sticktron** [comment]
I think it will work as of RC2.
#87
