### ISSUE TITLE
Camera app 3D touch not working

### ISSUE THREAD

**Issue by shakil-muntasir** [Sticktron/g0blin#98]
As I mentioned, 3D touch not working for canera app, without jailbreak, its working fine

**Comment by Sticktron** [comment]
Can you please give me an example? I didn't know Camera had any 3D Touch features.

**Comment by burhangee** [comment]
I guess he is talking about the 3D touch menu that comes up from the home screen.

**Comment by Sticktron** [comment]
working for me. no further feedback, so closing.
